
bases:
- templates.yaml.gotmpl
- environments.yaml.gotmpl
- repositories.yaml

---

lockFilePath: ../helmfile/locks/001-crds.helmfile.lock

---

# Install Prometheus Operator CRDs first
releases:
  - name: prometheus-operator-crds
    namespace: prometheus
    createNamespace: true
    chart: prometheus-community/prometheus-operator-crds
    version: "28.0.1"
    wait: true
    waitForJobs: true
    labels:
      app: monitoring
      type: crds
