repos:
  - repo: local
    hooks:
      - id: ansible-lint
        name: ansible-lint
        entry: ansible-lint
        language: system
        types: [yaml]
        files: ^metal/k3s/
        always_run: true
        pass_filenames: false
        args: ["--project-dir", "metal/k3s"]