repos:
  - repo: https://github.com/rhysd/actionlint
    rev: v1.7.12
    hooks:
      - id: actionlint
        types: [yaml]
        files: ^\.github/workflows/
  - repo: local
    hooks:
      - id: commitlint
        name: commitlint
        entry: mise run lint:commits
        language: system
        stages: [commit-msg]
        pass_filenames: false
      - id: ansible-lint
        name: ansible-lint
        entry: mise run lint:ansible
        language: system
        types: [yaml]
        files: ^metal/k3s/playbooks/
        pass_filenames: false
      - id: helm-lint
        name: helm-lint
        entry: mise run lint:helm
        language: system
        types: [yaml]
        files: ^charts/
        pass_filenames: false
      - id: helmfile-lint
        name: helmfile-lint
        entry: mise run lint:helmfile
        language: system
        files: ^(helmfile/|helmfile\.yaml\.gotmpl)
        pass_filenames: false
