general:
  root_dns: iglesias.cloud
  dns:
    provider: cloudflare

metallb:
  ipPool: 10.0.0.161-10.0.0.170

grafana:
  storage: 10Gi
  port: 30080

prometheus:
  replicas: 2
  retention: 15d
  storage: 40Gi

alertmanager:
  replicas: 2
  storage: 2Gi

velero:
  bucket: ""
  prefix: "velero"
  s3Url: ""
  retention: "720h"
  schedule: "0 2 * * *"
