#ENC[AES256_GCM,data:9SFN8Cj4enKRY4OhzKcO32Wo,iv:Cic2T1CbALzz+qpt8ir3NejckF/sHTf/VPRsF9zusYc=,tag:vx/ycXT2mOiLEB1gK9mWNg==,type:comment]
authentik:
    #ENC[AES256_GCM,data:KQ9+BCVbZBsdpvoxq6Ds1r3VJacr1o8hRil+gZF+L5x0gVDxXDU=,iv:UEfkT3CsnA7+fr7rKKz5klFuvDH8fzEX/1Oly+SzJe4=,tag:BHc+rrPvm+TIMUNtwsk+yA==,type:comment]
    bootstrap_token: ENC[AES256_GCM,data:wwGGw48G3dun+pIlfBRJGR2ANwels/1BJdYqs7lkhZ4jiYXgjIjhuRYjqGTTXgrtCH3JFSjUbBAG86yKE52UUA==,iv:P1YktexRaM1oC1z5ikNchszjOBKlraz8wqU6JA+uEj0=,tag:OHR+hapvmD6ovL+rVGoUrg==,type:str]
    #ENC[AES256_GCM,data:M4FU2BSOhwMwuhY7NxHrNFyUaXi07ZXzcrWg/7SxVhz9Y4Dpjy7G4Qg8U4rUDY19B4Vo8GjT,iv:CycpIM6NZsmzuuVb3WcrXWz0llPrpEnuzL0PBkFYqoU=,tag:dKCPntejHqg2NDyf4H0kSw==,type:comment]
    bootstrap_password: ENC[AES256_GCM,data:WkSxtV0E8Zt0zf2RStfSloVCbQM=,iv:BG+JINjASDRBwjMMzIW1Gpp63NqOIUYYTK2ulMwj72Y=,tag:PryZ/NSzxwkvUK+6Pzo0AQ==,type:str]
    #ENC[AES256_GCM,data:J48SBa5Cv4mEWmH8C0uzPyEGEYg9V3/wloEl2tYAifkpRHL3yAOqll2E2fDOFwE/PhbZ,iv:W6HqfQTYuC9ppvC53IX2RlWxjxjo93DcQnpwKCVdLFk=,tag:dkqtFYAnmWfI9d1bEXThfg==,type:comment]
    bootstrap_email: ENC[AES256_GCM,data:/yGq5yrD1ZU7Imp/jMOZAQgVhYP0hQ==,iv:i0PGtG/E1Z9Qb0yQjNM2HF8M78jm9Rdja/WxdLTzGFw=,tag:320V4f8+1CjUQYiiCT/Z6w==,type:str]
    #ENC[AES256_GCM,data:DA6D5cTapCqRKHUDBdPvwHvSZWfHvjeWJ9T8Kqq6AgZbDaena0j6kTb54YiXXhG4SVfel5STlBtvlg+OwTflLjftXNdgISEy+uy2H4ad,iv:hiuTCG1WxKjyVNhDTdyorTyW2Aj6sihi8ye39k0pB/E=,tag:Bq8uFEe32Inbq23ekYeY4A==,type:comment]
    secret_key: ENC[AES256_GCM,data:hjb0FkkDV4aVjHW2sdENLAKJKrRPy4xS2kdAlIRfZb+eg4Yl3msdhO0fw33hxPe4OmL1nm7NjihHL1ecdZtC3A==,iv:3iy/sVXnGWJobC+UixGy573MJc0l6xv9ro8wRS2xY5w=,tag:0BZe8RVg8kn6KQHqKn+NUw==,type:str]
    email:
        #ENC[AES256_GCM,data:IWgvOPFslZUeCz6S7JgnEdd9KXJUwwl0cOQosd7V1VUMpL2QS1HChHF3nNDDwA3SLv0BBZKM7w==,iv:Uii+JFNcOAzh3O/8Z9yPnCKEv3SiC12rHoIPjJej89o=,tag:gBnsquBnXnLUcwnLdoeUYQ==,type:comment]
        from: ENC[AES256_GCM,data:JWlZR3oJA0avrGrgraFx9P4Y14kDDn7jqqKmip6lV6JoKNXBf8UiXDiE,iv:qrwKTkGwNHARIvrMcllI2u8i/MCJjvUHku3mUPgGz0k=,tag:YHdo1f1H3jsBLZYwG5TQ0A==,type:str]
        #ENC[AES256_GCM,data:ywTPFGw5E419T92C0FVpURZ/nOmVbQ==,iv:oI6QNcMzXMW21OH3BcVJM7U9ffoxa8raPCo1gtzbyjk=,tag:7EL7hhnGK0c62lweb90i4g==,type:comment]
        password: ENC[AES256_GCM,data:XAVijfP4Huks2SwSXdgWog==,iv:5d0tSMroByC3LKBrkpHEUi+y5ShLa+N/vNbdEuKU1YY=,tag:CcfVVI/HdXwzKOIWg1CfKA==,type:str]
        #ENC[AES256_GCM,data:fqQEHwzB5ryOB3gSjZZ83x91LWRWfTdHhy5don9HqvSGPJOjb4S+vtAOH8P7Yjff,iv:yyXd2PhyHoNwPC7XYL41LPYPtxoRnM6HWCbqo3X6bHs=,tag:jVIhStPZKCNGI+AGbLTvnQ==,type:comment]
        host: ENC[AES256_GCM,data:FhODQEPujVXnKF2CdP2zD+Bo,iv:oAGBT57Imtc9/BNmzSYpTqH9+34UZ7bQI28jWYfVxmE=,tag:QN2kJRU1+TbFQ5V0F3KqDw==,type:str]
        #ENC[AES256_GCM,data:9DDyxG98lLK/wCFmM2i37Mo1lN39tg==,iv:TXi/TTy9kMM2VvkAYwj643Kj4pfOVU3WPzFTFq7Tiew=,tag:gHIdi+Accu9f+ZB1+ZvMPw==,type:comment]
        username: ENC[AES256_GCM,data:3AHjzPbo3RxzqIBLcwH99skyADBlRw==,iv:iR5g8VTdegYUEmrevJB7pf0MtwDq94xGlWCMVRfQPKY=,tag:AvVqxtmuqIUl1gyawC/aEg==,type:str]
    #ENC[AES256_GCM,data:XeJ5o26Av8+K2D0J9anxI9Sxy1o0FMUUXNO0XiN7fPa015qESy40mMkOpin91wCw1jJIRaApn9lp,iv:AUQ1IoLs/m6jW6wOZcckPMDrc9ZGk5zj1JdaA+vagHk=,tag:VMOoba1qtJmYDI5pj2Litw==,type:comment]
    postgresql:
        #ENC[AES256_GCM,data:9PFwLOojokjw6SHRvhKEQzQEw/Uq2as=,iv:NIK8cMdOc6pkgdhn18jXYO8Dd8NLn+Vb9r/XTKiuwgs=,tag:3wwb3k+4xfPgBC/5ijAHdA==,type:comment]
        password: ENC[AES256_GCM,data:WKIsCxxr+dzuCe+xtkGAYuT86mA=,iv:TlkM6sG5yQmlCeEBJIM/fowrPwujsShdzazZMGo+g7Q=,tag:E3WktHGVBM8elyPhWWvryw==,type:str]
    #ENC[AES256_GCM,data:ZfznACU/pNCZowYaNdtY/k1pYpLoJM6nU9gbTx9UYEoOAk2IV3oWyzqsd18LTAeKPdJMtl3Gkw/3LrMotQ==,iv:i7nI1RCASnp/PwkZCwd2Ywoxc0ppayRYGwaYkdPQGnU=,tag:JzTn4W/q12yW7YiYph5Fjw==,type:comment]
    admin:
        #ENC[AES256_GCM,data:xGvxWTdSMoSx2xyJwRC11f8=,iv:JJLMrTTQRg7cJtU5QaIX8mdr8/3ZqGXoFeUifYShYjs=,tag:uduwhFYa3YcbeKBFBycM6g==,type:comment]
        email: ENC[AES256_GCM,data:c+89PZ6kGm04PqXNpfREDgpd+3qyfw==,iv:cjc/i/+Z3Qba4jCAU31BS+8HU51IPlRHe7DdVr75VH0=,tag:phDnrVD5W/3OOcmigRaw9g==,type:str]
        #ENC[AES256_GCM,data:fzmtQF83iFW3sX2djU1q9pbesCI=,iv:ppWadK09RtZaQCBAPzW9gI308jOto+i+PDz461B8IqE=,tag:CY0XdQNBcgogyormPUaXdg==,type:comment]
        password: ENC[AES256_GCM,data:9fO/u04jfXPPQ8G72emZJ/9LEHk=,iv:J0EzrOeccEoqkaPaJii1IxJUJ89SeJNGrplScZKPXGQ=,tag:Ghvet+zM7fHasd+9vLjFBg==,type:str]
postgresql:
    auth:
        #ENC[AES256_GCM,data:U1YmjeeH2Snz5wa2jqwjcUQU+kVyKMKZYDIygr+5,iv:EGUtgUiceIaxzSc2NwgLvXUfnAw7ZitFxSitDG95d3M=,tag:vlkpkRN05YA2zED3uZv98A==,type:comment]
        password: ENC[AES256_GCM,data:CSq5sofEDrFoTAHP0MrQZNmxHTA=,iv:iuEjdQ4Auojc59Mf6OlrFDpgHbVKYhC1QTwwarS5V4E=,tag:W6Azk1A9tWUKNAkxQAQhhg==,type:str]
sops:
    lastmodified: "2026-04-06T03:23:18Z"
    mac: ENC[AES256_GCM,data:1tNYX4mBpJZeL+zjyyvFoCCv7rE22OsZJzOcpvFvUFbKdwrDb8vHZ3UT86GgIL5mKAUfT1LANqHgPPlkojQb5Rq1Jvwaz8rxiWgEWE5SI8suloJLfg+eUDK8BE7simOHgmBvAeaUKe5UyHL/l8B9+u9UP3PvG4PBvZojv6VcO1A=,iv:BcJSHE1XnWIMOKbu2u4zD6mtwNDqtFSyjArTLPkr8vk=,tag:AKnnaEpSuyrnknzHhENEVQ==,type:str]
    pgp:
        - created_at: "2026-04-06T03:23:18Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4Drti3Uh53xz4SAQdAlmXZdR0PmErXxly/sAsspvcjpAEUi7csZuYTSRcPKzow
            g5x4R4HjJ4d2cvAZtNk0VYcCcEri0EZoaljfsP84qHOhS9PM87K9ndhj2Cw/ZN+A
            1GgBCQIQFBi/Rnx2KpJVg7TmVVFFnZz86+F53o0xVFWvtjdVGOcG3OeQez/bNJrc
            klZrhfq88KPUMbEVB0fDTvMc/3G6wjEV+8ggK2+ftywA1gJPTtAxuzCdyl0aJG33
            YbOC8CzOHgq/1Q==
            =dQqX
            -----END PGP MESSAGE-----
          fp: 8152E60988488774
    unencrypted_suffix: _unencrypted
    version: 3.12.1
