#ENC[AES256_GCM,data:AZI5Cs1OCK7iM9S1Zq4WYnYW,iv:s1s4PkWMzt+e09AM4AMMiu3umbN97fLL1XN+qo5WzC8=,tag:5ngdq/sr1qwGsrmbvdCjEg==,type:comment]
authentik:
    secret_key: ENC[AES256_GCM,data:ZCqJQg/pKMA=,iv:NNiAMK2Wkw4Vh1MvbYnk/yp40lwO17uJcY8owgvSlyQ=,tag:l8JxYJtIdo1fl7nlJ/C+8Q==,type:str]
    email:
        from: ENC[AES256_GCM,data:VdSEG9PN509WMznFbRtaydOXDr8wPH3Nbx8rdOISHpx2DO26kScImF0T,iv:oFC9++tDNYWlD06tBfby2VHTJVf/0TtiShsfOMSq4jQ=,tag:YlcGsGgpYbfUFsPgngYISg==,type:str]
        password: ENC[AES256_GCM,data:ib7eFFFx9X+v2QYoF/SwUQ==,iv:dh6DFECWlOOdEmveKj5tY2CdU2b+EoxPhsjuJ7Uv8zs=,tag:1Xq1SL7XvXeuiNvF8pqPPg==,type:str]
        host: ENC[AES256_GCM,data:vtvKqMmhjW56MqDo3+z6T2LP,iv:BffgjpsPnKIlfn5m3HPlf1cjCYDQvf3Bnxg0whZwRDo=,tag:Bn2h7ZxMTBhRM+Td/BonVQ==,type:str]
        username: ENC[AES256_GCM,data:QJxkwENdKxwjc2/G0HMSOC9xhOPDrw==,iv:HrYIOwVNzdeKwKtX/jypQ+WlTxgNkKodL8sJIJXj0sY=,tag:W91CrWPYJmABzzFGvsAeWw==,type:str]
    postgresql:
        password: ENC[AES256_GCM,data:BvJoRQVL8EM=,iv:IVT55s1qP8wXbC+l5Clnw8oMwqIYtl00keLiuEHM/+g=,tag:e3TpgWIhAxUAZgww/krg8g==,type:str]
postgresql:
    auth:
        password: ENC[AES256_GCM,data:a8tQBx3EbVo=,iv:0uc/0UsxeizjPzojWVgOgKcvmxjj3sA7XsRPXUG82TI=,tag:xz21ZZvy2IzrOqmgKDoCAg==,type:str]
sops:
    lastmodified: "2026-03-13T20:29:13Z"
    mac: ENC[AES256_GCM,data:kyVW1n4hI8hF6VNsu5TYP6gi3KhwbUz+jVGybuqur3AtAuwfRezwE8tuby5dy5cdDb8O6XMWK1p9738PMnHrD2uDQBtRFtl2RJpxY9eYPe8JuD04vd2LV+GJLDR7ORYk9u4A81K79v5KaUb+VuCQVdIjsoFSxXRhtcZL6D+9vwo=,iv:yKAwsrdYcJafKhOaCLc2AS1zXvNeHDNvTyh2Gb9+ASM=,tag:ldD4AqNEwzx6wf79+BHnpQ==,type:str]
    pgp:
        - created_at: "2026-03-13T20:29:13Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4Drti3Uh53xz4SAQdAO4OxAHCUtvcFojBmlpI47FYjVBQq93/IJY/ZD/4c1GQw
            /TjpNC71EodFNUKSJ7Y144HxhRJhLLiaYqRLPt+WdM3+bCiBHqaZoeYZCOL9Gvzc
            1GYBCQIQ7M17l62nvKZjYKvlvxLQTjXspDQLK+CAQTZPFXAl2lFarkH+eRJBOCK0
            x2dLQVMpl52pjlqR6An1RUuueMgK0X1M2rPTyLEYpFAr8NHvFfHVFxmAzyzYmCDr
            uBTXNzZ6QJA=
            =qxoW
            -----END PGP MESSAGE-----
          fp: 8152E60988488774
    unencrypted_suffix: _unencrypted
    version: 3.12.1
