#ENC[AES256_GCM,data:GBj+rObYN3sgY2jH3aqwQIS5,iv:3wYK5YnxxAdK+FN5iSOJbQX3pGaCR9Avld0yRZln4xg=,tag:sybKKOhws9Llbw2Hug5p6g==,type:comment]
authentik:
    #ENC[AES256_GCM,data:oJSi2WZLTLIr3Q8yjhLjYgRF8qCL6BO/Vya1JFORXHxXv8Gj7mM=,iv:X8eyFPpAwvlwa1TCUst4Oyalpt/Z26SMkVUCIvi5S1E=,tag:Z2JjA8OpQGtAjPsUaNaKTA==,type:comment]
    bootstrap_token: ENC[AES256_GCM,data:zDGIrFOT3l8nMWRXd9/ybg/TzvL10FMKuzlzTShlf2ZRZ20zFCx9KoysWLwbB5u7hdLz96in3nQiCbfuJkeJkw==,iv:eZPsd0k1JUqIvXK0KG3ido1z3io0PC3QfgCUX6ahqPI=,tag:N8Ts4FkxIwKimXSpxVt0iA==,type:str]
    #ENC[AES256_GCM,data:AwjcMmnzU/tno5bIZOKh5z1pa5iniimlXn5xO7nQmsbHvoBx5yHudaeTEdmlrmiG0S/qmWSJ,iv:dNy5oiMFuV0IiA6Ev5Fi+/diuo/iOkPXJwHvc0uHQsY=,tag:FHkc+uaP06W41rD5Ho/+AA==,type:comment]
    bootstrap_password: ENC[AES256_GCM,data:kTIhqICgJX+kl7o3f5wGmk36270=,iv:qGeZwvO1GakhFo/vWz07Ozu+2uC2FYqVwLFmIb7GuMo=,tag:iF//fT5EwvaV6Y6NgheCCg==,type:str]
    #ENC[AES256_GCM,data:BC17bhUlJr0km/f0zODVosig05bQqOzNqysHhUDpMKQgkoi5UG+TP3EheWDlm0fZV6fV,iv:2cgaKzMdapj0AYjEnK5PE4Xy9WANWFqd1bFEPJIDl9E=,tag:UqE8XHs//abb+SfXVIGpdA==,type:comment]
    bootstrap_email: ENC[AES256_GCM,data:+7vsmSsbvl6RdeFnM0AUUdeuo+ky6Q==,iv:xBeNHdAg06w9t551GjmXQdAAiHs5gQbdCTkOT1+tqGI=,tag:q9TZxvrXarvSa4nBPE3sxg==,type:str]
    #ENC[AES256_GCM,data:OxJpKyJ+ZYnKFGnIdIW9+yvDJ4ft1mXCVnRTa49IR0F3VBcuKIkD5Dj9WgwpQeOuFXHiXnI2/B0dg5SIQD3J/lBkGcdFCOIO7nv/yxv1,iv:ejzZlRD+/Zdimroyqk4yByXKibedi8ShIIr2umDDyTk=,tag:ptCOmNhgRIulHuwysZSwnQ==,type:comment]
    secret_key: ENC[AES256_GCM,data:3dcFT8Y+5BV8uU4OOwjBW27nlb2aSVc5Zr57Gw9HmLQI8AzNWw1n6XuBLaRLL2pKzraV/fgmWaMCQ4T9EW6phA==,iv:Hy5SIYe8TWImka++Vk5eujm3EF0+bhXzJjx4xjK/Trs=,tag:gB/gSiuyEIYYnmsrBJyBTg==,type:str]
    email:
        #ENC[AES256_GCM,data:ioH47vQnGHywg7DMvSGcUzmZsJxGtsZCShzjWk0p/Cz6zEZ0va1MbBVZKSqQW1cjtrfRVX0ZqQ==,iv:5HVKDWorDOvQUobrscd0WKxYlY7VGvFT9Ykl2ceCaPA=,tag:5qm3XpPA12FNa+qYwrNr6Q==,type:comment]
        from: ENC[AES256_GCM,data:EyDd9FsQmU/QcwJtcv2UheKYXcWx27CqE4KTVO1Mg0yApC3S/vyYma3o,iv:DIhBYYYY+hhteR3Av7WN1wsCCoHfkLhmMPl7CeLmk/E=,tag:1QvEkJleKq+Pe3cgY9YkjQ==,type:str]
        #ENC[AES256_GCM,data:p/K3/SxQUgbYbRAgrd6m/kwVgds/Cw==,iv:a+PRispHlJ98pXn+pybb4DojIhVbtvQQzK8i77HRN+E=,tag:fjEKYnydgegcEf+u+kxIuQ==,type:comment]
        password: ENC[AES256_GCM,data:22k584hk+k4CYyXer76uBA==,iv:7TOsJBT3/ny/BoJ7zcBO56Lh2DNSNlwRhSQ+BdHA6rg=,tag:ClYWjHMrKrDn2R2OCQlZIg==,type:str]
        #ENC[AES256_GCM,data:Fd75IuddTP0Xo/AkOs4aCgMih1vFzL3hI6uuLMdMa9S3WymiCPAsRoEAGz6/hMxh,iv:1Jm9HLM2gqBrpXBvwR0RMimewsd7VxmUt6nDTX3h5nc=,tag:f+7iCbZfZxWqN9UxLJBINA==,type:comment]
        host: ENC[AES256_GCM,data:LVvDYon84gaqmOQMPF+j1TR/,iv:5MS4UmuhOciAdnGIReXRnSIgvgx4fYKOIDsIZaY1Bf8=,tag:BDc4mKG+pcE079nS/GcN/A==,type:str]
        #ENC[AES256_GCM,data:3ffumHPudSgFWJ3GhldtZMxZlupNkg==,iv:IFDNoYauP0cXy5vQXnXX7TbEmA9SITp5VOhN3Lfkbq8=,tag:Q766h/8rPZCl9Y3Ug2O+uA==,type:comment]
        username: ENC[AES256_GCM,data:Q1N0QZ4AnuSkRGbTvj3iC0ieEc8Hpg==,iv:hnebQdVtZwI/GzkhAi74H/Ovr6RQ8W5EBdDjrOoMfdk=,tag:Hu1cBl749CN1FsIY8vUX5Q==,type:str]
    #ENC[AES256_GCM,data:AMH/TqaYVEIpfkmDNKWHi3xrfpYddU12qMb4/UCTjNeYsT0LdqeWmEZVhmARJqP7Zuyf1L8krFaV,iv:12vaatukK8rWQjeEFHwa5ZMfipBL8akc1yAo7fu+jpg=,tag:0ADRFVo6DjEtvS4GQVaaUA==,type:comment]
    postgresql:
        #ENC[AES256_GCM,data:Q+TWHxvV+AmIUzbKmMLjoS0bk2cL5NY=,iv:I+pnyg80mm8ITQs7a1Q7TpZfjcEyVej8n929oS4u6PE=,tag:nrNOhakgda8jM4gwamBjmg==,type:comment]
        password: ENC[AES256_GCM,data:nWgNL2pAUJmy3LbpKNJ0m+rY1Sk=,iv:s5L089nTyHu4Oqvm9rEZSgx2M0EZPOubFMLoGixDC20=,tag:SEeW1cDmoph0iHzpv0nX7w==,type:str]
    #ENC[AES256_GCM,data:H3tkaU2QlIwtGeGzoN/s4U2ilk7vqfd5/738TL55Tn4WAM0p0rutms+HrbSr7xpRMD/Qp7lHxHyKNWr04g==,iv:ze+BqR3KUX025Ii/Q1ieEp1b+GISD2im8VjvtJvgfPo=,tag:7VU6VLPgg5xz2387P6J4QA==,type:comment]
    admin:
        #ENC[AES256_GCM,data:HH+HHQV6iGshE1O8TdtdxMc=,iv:h5jgEG5ds0L+Y9NVaPm+CkHIijcHXOgKWdLSGGAF7KU=,tag:0p0crWXstXR3XY0yDnvcEw==,type:comment]
        email: ENC[AES256_GCM,data:wD4CcZYjib80fMaydj9fuzymOouoyA==,iv:m6G84GIMhylguSgFkhFe0v0gnYPG51CGfs6MKoN/2Ak=,tag:mf7SVzeHQ4QP8iC9R7OMqg==,type:str]
        #ENC[AES256_GCM,data:oUgsjBAZ35pOZbasty9u6gW30fQ=,iv:CIJRdwm+qXcXkmJ7F52f7RVf+b0HbFcRFjxVr1NEs0c=,tag:APQUVD7Hff0IXGXQi/PbRA==,type:comment]
        password: ENC[AES256_GCM,data:92YIhr6ttFlj97zDA22fTmuN3vU=,iv:FIc9Ft4r9TZQe8FC/WbWgaHUHVrOF7DkDvZfO4yKjbs=,tag:+jazGwfWhA9VCVOnnipwTg==,type:str]
postgresql:
    auth:
        #ENC[AES256_GCM,data:r3gsKcDPYPNBd/bN9q88ged/YRS1d3NYq+i8mcZu,iv:o9JlQiMDodVolEIC+FdwAAxuU8pO+rjnSpNnlCfYK0Y=,tag:YgjCl9/dp4y+bpW/zPAohA==,type:comment]
        password: ENC[AES256_GCM,data:8bjIUjZFTXpcE9Q0L50MLKIDWUk=,iv:Tq2RGE9BCxgFSDLD683ftRnxU3dc++SvtAJb8ah4P7Y=,tag:5K8m0WjkHz9UTDgejHz8DA==,type:str]
sops:
    lastmodified: "2026-04-05T02:27:05Z"
    mac: ENC[AES256_GCM,data:21/aeyeQQniBuDqtoCiR447yF2aOB8YicXtUOCEGuqnOKzFck2VMdxNopncGUPd406g2wY5hGwZy6p/o/V/1ur84/Rsh1KXbhTULHhRTht0alxas/0y+fq/rrUGcX2rj+45BS0omkk1TI4Kh33qLSAcM8YGaOcwpvvV6KcMUNxY=,iv:2XJN+q7dWHGcpXLXZl87g3lpYFUheGHtc1mGTZ3CxVA=,tag:JM+mHlyg6vTgdqBaA4R5tg==,type:str]
    pgp:
        - created_at: "2026-04-05T02:27:05Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4Drti3Uh53xz4SAQdAfaYlecUpdaWQDCX0xs3ns/71DPBUK5r5Xn3RFa6tIHow
            QIo5kQ7YsL09DvqdlRFnsKEE4gfbZ+y7MP3QvciQzk4SCjwyA4dKHp9vHa5v7sqQ
            1GgBCQIQOqp4u0tJerdpo0vu3LJS/0i5mXCzsj2ikNBIlSQshycyYzvA+/W897mM
            Xngf3tXUep7Bb16DW1WFHqJgelsYCEIhC/tGxaMnq4el3/Yhlwd/qgZ69aW5rZNO
            niQ3stP1dg8s5A==
            =B9wS
            -----END PGP MESSAGE-----
          fp: 8152E60988488774
    unencrypted_suffix: _unencrypted
    version: 3.12.1
