secret:
    token: ENC[AES256_GCM,data:g3SE10Kr1OlecFchsr2FsF3GL7BViGdJtJ+XqkQQrIyJwsV+Ii2T9eN208WzTLupNatP0sU=,iv:MQSEqIicpzhiqZMz2OwQ64wBXlD8ClXaoBS51AkzhQ0=,tag:ZdBuP+AmaDY27UNeUbI9/Q==,type:str]
clusterIssuer:
    email: ENC[AES256_GCM,data:kQdaEyDvg5YoW8VULKjc+Wo6fNdRCOqhs30=,iv:T5t14PCgh7CD7iUiVDbZRNaeHuVYIPraI+OlIC82XFk=,tag:du260F9ilnKOrPgsvFoxFg==,type:str]
    cloudflare:
        email: ENC[AES256_GCM,data:aDeWqjYHwKX9a7zb82LUrwh0TaY1TNxmjzk=,iv:F/JgR+fQ9bdcxGayMspLEUqD8+jz5HEwJP1sYjwa+UM=,tag:Sgq0rHhqLSedK4rkZ/x0yQ==,type:str]
certificate:
    dnsNames:
        - ENC[AES256_GCM,data:ZUzHkuvL7f2+uy+XL0Q=,iv:2UsBCMf2esOCYdz9kEI6Ifk9wEy1rqULOorcXN5P1J0=,tag:H5LNLYDG1sUc2WFyMbWqaQ==,type:str]
sops:
    lastmodified: "2026-03-20T05:27:17Z"
    mac: ENC[AES256_GCM,data:gEVhOWsX4Bl+djSvZGc7MAhr5LLeDc4MhUJXtBXdgE4WOtob5mRHFITjAOw7STTYqEyMTrsXgyNk76qHnGJeNqlS43sAVGORGHZS27AvglpRMudRuuMtf8paQAEKmRAWjyo0JfO6O8A64nfnWNYQjbUH+Qy0EXreyWMO2ux2Dqs=,iv:5vdBBfx+A85iyprbb5ODzevUfal76Ho8LLXEKaGVBTc=,tag:hPGQvah8F+oyzlMG2abMfQ==,type:str]
    pgp:
        - created_at: "2026-03-20T05:27:17Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4Drti3Uh53xz4SAQdAZRtic4IaKYyPf48jMkrxV0zO95UPvw0UT/pPXvSAz0gw
            3jzO3U+JjO+Sr3e3SixbsLW477a+E9KGmYjnTpOtYEbUHs3KClmNgTubZA0/wkHI
            1GgBCQIQFuYLmLW3SLCOvcGycXK6GcHNl25W3PXHl/5gTLX1kI3m3yIqfZ8yfCsO
            nylUzPRdNmIC3272wN1ho17oFa4RkMMjTDiR6V2H5bMP39+fMnNkK5emDeeSRkJX
            nrF19kEwKhMzrA==
            =XRl7
            -----END PGP MESSAGE-----
          fp: 8152E60988488774
    unencrypted_suffix: _unencrypted
    version: 3.12.1
