secret:
    apiKey: ENC[AES256_GCM,data:yf8doJDoq3Ch5NHOudw0bXP4ipFgS04+1Ez9Htwp5T2Ce588N6T73AX16+LPp/3rNeYN7gQ=,iv:OhKp7iya0NxwzWxDl09EQQh6GLiA6ZTgcjUmT4nN54A=,tag:yDeg8sncfTgjEc/E0hzFUg==,type:str]
    email: ENC[AES256_GCM,data:XdVdr9v1OexpASB15dWwqwpSrVOHecd5oXY=,iv:PuYfPbBgnQr4nBSBy7qZK7+8xXXJrJr2c2hVUyqOinE=,tag:Yjt+Hoca4apYlL0SvgWW5A==,type:str]
clusterIssuer:
    email: ENC[AES256_GCM,data:DOs822aLiZFdnIWWvypauH+r2LWcM9Mifvo=,iv:rCiNJPAGZsW73fnHJUE7R/svZJgG7lXGJGJWJ+a/mL8=,tag:ZIH/jQwH4fxWbPFYnDlccw==,type:str]
    cloudflare:
        email: ENC[AES256_GCM,data:e2Gdkf8xvH61mRBdCAZl8rcZlN63Pycs2SI=,iv:vTgeBDUkBVz5/RKWyjZpLVMUXsK+D35P4uFKAzdrciY=,tag:BEPZvRWhbYJzKqUs1Po7ug==,type:str]
certificate:
    dnsNames:
        - ENC[AES256_GCM,data:sfih17y0kM8etqsmo1Q=,iv:gkVFrdjQv0GtRsVYagtoYkx/5ESDcNKjNVf/gIsjPN0=,tag:1oYV2B2l0Gl32b5k7ne7QQ==,type:str]
sops:
    lastmodified: "2026-03-20T13:26:35Z"
    mac: ENC[AES256_GCM,data:8Iwy0rAZ1A1pp1S2IDgsz8PEct9b1vHlvDSPAFG7/RTAn4OLQ/S8S40PdZffDg13d4QCBFnTXDIIMfXJII5EeRe1IzkLaAUDe2NjiG4KvLAkd1L95pzVkNRc9qppkuHHWk4/a/KKpJjm3G6wgHvowhAkZemTPteVESDeBU/Znvo=,iv:wU35I+CPLLEDI4TMnk/iXkXaZ0IinjtlHYs9jqmyXUo=,tag:XL6xW0+VDjEUuIuQiEEAog==,type:str]
    pgp:
        - created_at: "2026-03-20T13:26:35Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4Drti3Uh53xz4SAQdATAygD6DZn7qgO9ib/Rga5gOH7ZBrhlllCVD6lAmBVHEw
            Jsf5VAGy80i+CN6jpydas0K5owsd3+O9RI16whC9U/bsIWvds46n8Q2cOY+HB8xJ
            1GgBCQIQttT6LWoxh4Xp81wFMQILMadq8LxWpfz+eHkDcR0SHoLDP4N7xhHi7mCF
            5GNBbsBfWGinco1Sd1y+OFtD/lPlbYGH1a0r1TP8L1aA37nD6gbFXUi5JcEBKH5T
            oHgc51AvnPuqOg==
            =2GRu
            -----END PGP MESSAGE-----
          fp: 8152E60988488774
    unencrypted_suffix: _unencrypted
    version: 3.12.1
