#ENC[AES256_GCM,data:hjip4PhF/4fWkAxOKYcY5w==,iv:Tasvk+xCYY1GSA1xzhkaihDy2ZveDCX+Nty/k6hA8sY=,tag:yasxw3pNF1HEdK0ioTI+lw==,type:comment]
grafana:
    #ENC[AES256_GCM,data:9mQDcBZwK/kggN0WWJKzE2JkrpAsXLAXBQ9azet2dvqUQ647v1y12BYcHuRFXXUkKA8YY1wV7VBnVK0St4fnSYzP9UQE5A==,iv:K+uUkq6GsxWb5Roq9YxmQSZEwIps8/Qcc7HVjJLwi3s=,tag:BZM/8E6CfVv/ac7PjNWTgg==,type:comment]
    adminPassword: ENC[AES256_GCM,data:kvBN7LYeLXpx/HwHirSlkKerXpo=,iv:92eEjvsse0M8q0UYWvMH7U0Uv7I3Cmt4oqYKUG2Yp/4=,tag:5tvDaog7zNVE1S8FImiBmQ==,type:str]
sops:
    lastmodified: "2026-04-06T03:23:18Z"
    mac: ENC[AES256_GCM,data:SghWV/FMa1v1aqMLJHK8II+wpKzeG49N/AYMSwSSL3KYw7HB3MY4URliKrxft3IwpuHEQcqnWkzd+G/52cxtXpQow3MC6xP208OvUgdItlDqzqe45ts8KbgkiGPiaYVuaSPMmAEuUfNZrNn4Txx1F7vKbz7f7eDzvh4K6H3XCGo=,iv:gq8uFQsjFZcJwNswQKndg3CDyAWldmfUdviMin4cyaY=,tag:aSqe711I6sSesBYimat+mA==,type:str]
    pgp:
        - created_at: "2026-04-06T03:23:18Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4Drti3Uh53xz4SAQdA1388yYIHKL5evPrivHywEzBx4C3PKaGNK1TWjZjEOkcw
            iZ6wDuE//QbmsFDDtzv7EZpFOmwmFuEhxpXWBQ0bZYYCK2ti8JIyKbgAZ6fZ+BfV
            1GgBCQIQG0QrPD8BYYjCOMAIu3aD5jaiVdZHBpNt4BUt8cPXnJDFu9elneLYimFg
            vCzr7SQqcUaQqRKCMecD1D0f6/SA6ipTOaaVSCp71zaO9TluHqFQyXEDUBcHDIQV
            EgXyWtqF0+r8pg==
            =nBtG
            -----END PGP MESSAGE-----
          fp: 8152E60988488774
    unencrypted_suffix: _unencrypted
    version: 3.12.1
