adminPassword: ENC[AES256_GCM,data:QB6IdD7ZAco8WVL15n9uNrBqD0DBYnOnw1N2X8ayBdE+vSqVE+uRhym1ovKeSQ==,iv:gITp+2ArSTapivYs2h8PqpB5TAe0rGSqrMmpDdxzUFc=,tag:JvI+fbW506CEmPUj7ew8fg==,type:str]
sops:
    lastmodified: "2026-03-12T23:53:07Z"
    mac: ENC[AES256_GCM,data:Z/KSpt2lRaN1W8SfKOntuCUWM17iaVmASrBJ4sPrzngESBAHruqiTS5EqoRwhOpN1xUvaFO66V5fWf40xUeN1Iuqa8llbynxcPSdbIxf2HhSBM/8k7GWNtEzQx6XAj2nI8hYMSJcSPP1wVnvqIUEMpfFVpZwpCO0wRJk3X6RZT0=,iv:12kRSPQjnTKRvlZ0No/h+vvfOKziY0SNenrNcNsPwa0=,tag:aYn+QNP9FHMVDmsaFGz26g==,type:str]
    pgp:
        - created_at: "2026-03-12T23:53:07Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4Drti3Uh53xz4SAQdAfpWqi67V+OZ0NyWcfcjmG4ymc7WpLs4UiGoQR0x3Sj4w
            WjElnVlYMaU16l2hpR/pdOdLwvNZEOdfHyOIn/f+8RAyTqOc1bwEEGiIcoL+b9mQ
            1GgBCQIQORkIEuayqGGgccSJ+bZ+fJRKj5HuyAPgdVEf3R3KZiXZdfv274pg37LH
            pdPqZYwlM6WtHdYW5GWYuZZ58RjBbUVR5RLOsZUYbzxkx2N6fnBcPUQMsn0Mr6oX
            0Jt1bRFqfTgHOQ==
            =Sfa/
            -----END PGP MESSAGE-----
          fp: 8152E60988488774
    unencrypted_suffix: _unencrypted
    version: 3.12.1
