grafanaAdminPassword: ENC[AES256_GCM,data:9Q8rU2fjGn80lYZio+x4RXfcPMJtJKY=,iv:cW4j/kJQP6mJGblCA1EnivQluVFkqTY1mjWBZ+pUfGM=,tag:4xiErYvjSprFbz05/OORxg==,type:str]
grafanaSecretKey: ENC[AES256_GCM,data:gEolaZhlz+8ThUsgYOveADVSSL0=,iv:CQWOke4GJ6a5+kZFD4yGlLtNSUpg3tyzuDPZ+AV+TDQ=,tag:GisVtF7Y273cC5dLxDPBtw==,type:str]
sops:
    lastmodified: "2026-03-10T05:07:13Z"
    mac: ENC[AES256_GCM,data:e1AOGHavZV5DL14LYQFd6IOKa9G+cxzALeaCmDfeIcDE4bgEjLIQGWEwRGeSHn1U8P4XO6STygdOyXS1f7wLXBqQ30tX/RWFelGHEa7j6RLfGSK4HnHsSXAMqu7aYhm2+eZivWyyOCpCp0mEfbq/8Ze5kK9I6gITTTDGfwWHxcs=,iv:RfTVXcAtd7qqxXXRkhjV1CYtHFDPWJwAIsMjYY4m6Iw=,tag:jTQyTZ+0Hfje5Ld5gORCWw==,type:str]
    pgp:
        - created_at: "2026-03-10T05:07:13Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4Drti3Uh53xz4SAQdAc6nnC1JaTx2rjv4MQc7jm1qW2maofvc/0Njt75h4wyQw
            RXsMVhSMXgymap57ZiU+9toFWEoGALSMzawmDIeBDamTdti4bo4zs3+nqqDAHa2/
            1GYBCQIQmXFQm8R6DyCawtFSmbucC9ZVOBicxTJhBZYwPUOE23SI8B9OZqSmSUtI
            NbLIWazl6Pward019VvsJaNc1hh6DjcOpG93C1yqzzMg+gjoomOZf2RSd2X937gP
            hmJMjxrozg8=
            =qprM
            -----END PGP MESSAGE-----
          fp: 8152E60988488774
    unencrypted_suffix: _unencrypted
    version: 3.12.1
