#ENC[AES256_GCM,data:6QWAs7wvqcT48SSkOV+x3N5BnBhgCbMwlw9FycGwdOpPE0gwKexuiSeM6uP4VT2kGG0mQfhwlFWxTl/SHXMUqW0oach8SyZKUG2hRD3BCDnnouRlwEOGYfJ9F8jPupjV7BOaENDdMnlK3W3T6wwcLqO7ZDM5oEtN/CDSxPjdvfbrDZq5S7rBJ7DA3Se5DapKz8MlfUClU8rQ2TUc7ESa,iv:IsOU/r6Y3N1C2jHCu+rGZL2pHxBK+IlmG+h7T7LQvCw=,tag:hNbMqRDxEskAdqWbzINsHA==,type:comment]
auth:
    postgresPassword: ENC[AES256_GCM,data:AlkeaSiBhFQ=,iv:fJ+2esJcvdR/BIEga5dprkuLYBuzc2lL7dHNyAHqIJ8=,tag:PFs7zEfNKQieUBfFp7X3cA==,type:str]
    password: ENC[AES256_GCM,data:xe0xRWEo1rk=,iv:SZ3ZY9WYQQY8CSZmXfUIZGoLTRycOpM4w4QCQ45SQdk=,tag:Dp7sjEtJvuv0bELSZ0/heQ==,type:str]
sops:
    lastmodified: "2026-03-12T19:23:47Z"
    mac: ENC[AES256_GCM,data:F1HM11ExbWNF9hs1ixhicm/RiS+g5+HPmvbznC5smC2Q4avsYW01hiF/NBKh5F3A954SA7H53cCPstbLE82fZOc+iWzcO+VLQlaF0aIykXOJJeb0SKMS/PQf91FcN0WxNswIUjElgYtOht2uHWcbpFDhzaeO+n/yh19m4UYC6kQ=,iv:3gZV0gvb0PAKJQFubJARotKe4z287otVhmAxvIzJOW0=,tag:pAI2dDwKLt/uF6LtEwQn+g==,type:str]
    pgp:
        - created_at: "2026-03-12T19:23:47Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4Drti3Uh53xz4SAQdAXW5UuHMjYj3L3rZ7XrdqsmN+MrGq4UG42+KULqSlhU0w
            ed8BXc+7nURQId+qBr9pQKms2iAD3ZRtdUREyvJnbB9/W/AEZLHF4z6INwLqH+ln
            1GYBCQIQzV5BHhk3GyERX7ZLNmXitBuKqanruaRP5bPBC2NBfOkhDriwtW8QmEu/
            mM1uRz1lR76np+Nms/Ps13IT+VE0/xPRDTs51l98b7+k/PDcnISRlbhxK7xKv6OO
            PGN878B4qtE=
            =UwqB
            -----END PGP MESSAGE-----
          fp: 8152E60988488774
    unencrypted_suffix: _unencrypted
    version: 3.12.1
