#ENC[AES256_GCM,data:EBtRGonByih7zm775XVNPRY3G4TtZThRpg==,iv:jayYAuvsuxbydmXxZv/IDudRwBpPwjtykOzr6Blq9lI=,tag:6V6C9n/sytKN9BPE3OcaBg==,type:comment]
prometheus-stack:
    #ENC[AES256_GCM,data:NoZZlk+ptMjd08asn0KUmyfWMJLIiymTWNTdHEgkxhbg2H0ykZAdvbIO86e3Oyhowg==,iv:xne0K3Gzf6muFZNN7CIq61ZhX2YKVOCt6sqKaEEYE0U=,tag:+Y/4fMoZiBNJXS+o5YOVCw==,type:comment]
    alertmanagerSlackWebhook: ENC[AES256_GCM,data:s6mmqX4QgVh0yitM9/oL,iv:4WUkC6zlv20Mx9WdTXNQty/037gvf1DiNGxRqNiI3Gk=,tag:WhQ19P2vgqIG5CT+T8pqNg==,type:str]
sops:
    lastmodified: "2026-04-01T17:10:42Z"
    mac: ENC[AES256_GCM,data:OC5OcyXkEPlM90pv7wxhbz7BmsOPAT+igEkTXWCeikkjGIk0k1HYA4gIUIqMSc3GstEQOhsr9Ag88rKRAGsH9zNYNjXQZ88Lq+77/eFYuEAzWMQSSJjChiXdFkGyzLAnulEyD8+Ep+N2DHlFcz+RwjD5kTqijL/ftdWBr9BbC58=,iv:x6n+COa2o7LHnqbyreGx8gexlM9IxTtlmywobIOm2qU=,tag:+k6KWC8NOTWFiZX24rvO1Q==,type:str]
    pgp:
        - created_at: "2026-04-01T17:10:42Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4Drti3Uh53xz4SAQdANIQ7toVeMW9gUajclQkr2lvH/gQtL/4jzaU+d0ivXFQw
            IOYQojk49mKMHQuFCW4RQIhm5h4TCzoVTe/5CtL0Upq2kHQNZu3wSW2GYJ3jreaj
            1GgBCQIQD8V5wUl6RSkV5gXL1kP6kjv77wilw3dwt5pbfHPAzkekrhC+INm4E8yu
            q6vZUgg++2WSGgUwjAMxHrZ8XwA7+n7WOSosstSElaFsvAH6WXrot6AEZ2wscVJF
            h5kgLNeFlts4og==
            =yz1L
            -----END PGP MESSAGE-----
          fp: 8152E60988488774
    unencrypted_suffix: _unencrypted
    version: 3.12.1
