#ENC[AES256_GCM,data:AKILUNppp9y6bq3kg1wNKXs+HNsQWavs0Q==,iv:mrhtYHZEMi/RfK+LOHtFbYUn1QnyJUCoI/EiJQsnKnk=,tag:gb1elbsbKtc6s7tpxBZpug==,type:comment]
prometheus-stack:
    #ENC[AES256_GCM,data:JtwgSirWO++F6u58DXGPQMLakQca9u/1c8xmg7LzWI4yHsETWYsff5ONtLTqJblmxw==,iv:mw3/w+73MpX32tWpXXfrg/RlhzTYtVQ3VPIGCA4Vavo=,tag:3+O8xyuvdTyRXUV42pbR0w==,type:comment]
    alertmanagerSlackWebhook: ENC[AES256_GCM,data:XKibcElKq9i+141E/E6U,iv:fx2IcwpLcihvG8fans/3+OPDpyPu9l344JBKDxXZ5WY=,tag:LagdVPt99A4j4vrHuLG6Zw==,type:str]
sops:
    lastmodified: "2026-04-05T02:27:05Z"
    mac: ENC[AES256_GCM,data:RKrsitrYOiTdQh4kcuRsbh481Uf+JuBjbjlj0wx4sxh2AJmRaGzwdZp/04MtVN9JWVcojJZQb+CC787IRBbtJWe+zXxwa+Uh4h/OCwUUQoCxDgvT1SzDkcs7i3Z1h/qw7dG3x2HNGFNdqAqW/u3gdAQfNRk8A8Xo+tuODXZdyX4=,iv:phduqGW3WnuLrjIUv82ofTLJ6dkQKPGKd9EeujrXszw=,tag:FS/QvShH9UKuEDtuW0elLA==,type:str]
    pgp:
        - created_at: "2026-04-05T02:27:05Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4Drti3Uh53xz4SAQdACRe03V7yaQQ1Vo/oLao8zZNMGNGcYECOdyvihApvaWow
            +WfEDxgVHJc97n+fUwZkkg7f5ELMMlzY57TPo/gc7jUx00rDB5vANwZgxr9206PO
            1GYBCQIQaY6SZREgyomP1Y0sW0U6IsXn2DDKwARQb7yZRnFpwkVA8Ndr8ek2uH1F
            ozcM2AmUJHwjd94yUt1/lTkLUFQXTu4MdYdNs//rULMV5ieplhGrLVKw5pT4uyCF
            6MLuIHnjxwc=
            =Y0vJ
            -----END PGP MESSAGE-----
          fp: 8152E60988488774
    unencrypted_suffix: _unencrypted
    version: 3.12.1
