#ENC[AES256_GCM,data:+XDb0h0iOpT8YVFtX1kCCeyHv+LGSXumSw==,iv:8I4xFXY9B0JFXFEZuuYg3eze6y/Itu1WUXfTwH389Vo=,tag:ACeLExCYYXmXqQWQxsA1tQ==,type:comment]
prometheus-stack:
    #ENC[AES256_GCM,data:S37IepXM9MGqTSyKZVqmd/36IeXMuJIoEstmVUViz78IhWdRSIIST8gQ7tHJXbfydQ==,iv:fGDUV3JEGs7lNUlRNzD7R6KVlOPQhI2Z3QVP3Ka8/OQ=,tag:ljDcNurO8mogN4SeHe7smw==,type:comment]
    alertmanagerSlackWebhook: ENC[AES256_GCM,data:bq6z6lQ93A6BxI5NEiom,iv:kKEHW7YYrqsIgx4Cw/bSeLlwwE5qiVLDB9bhdBEcBi4=,tag:t/M/aaWXsQ6vqsgu1/rvgA==,type:str]
sops:
    lastmodified: "2026-04-06T03:23:18Z"
    mac: ENC[AES256_GCM,data:Wq/7ZudcR6iurq9rrWLcwZLKkGzjrFA32I1QnLwcT5SZwjHcAVM2yJMuGjJ3/hsV2CZH8KreHavL6qwJ767EiDFipdjPISNAz29fYcWrZt5isBtPmfI3nfanfsgi72FI0dZq0JWgoiQsSl0nc9CBIv+leNhZKl8HFtaEH5yOM3s=,iv:bJGbgcT1gtY7u9MCkt7ZcsdHUR0hJiNoKS4n7mq+mYA=,tag:9wHiFPHRofYoo12AFd3JFQ==,type:str]
    pgp:
        - created_at: "2026-04-06T03:23:18Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4Drti3Uh53xz4SAQdAthtkKlrW5KMDWL0IFd4AtredG/5Mlxh/7Vj15dU4hyww
            VwtlAqXfAQDdeKTSFfUNxwAbPXX1MIA9deJbBKgbbEknMSGXWKVHMJtE8cEPF1ia
            1GgBCQIQr+g/ES/J0YMtcut02MbM8uqnNt8/wHIdqJtoCXj8PI4IMpMekObfpjap
            uGC0oji/1kE6AV0gak+gkDAKoVGWkT18IT108uk0MsSK4Ain59/YsCnuL0pD/OX2
            NfoseWdeYJ8TeA==
            =eGSO
            -----END PGP MESSAGE-----
          fp: 8152E60988488774
    unencrypted_suffix: _unencrypted
    version: 3.12.1
