#ENC[AES256_GCM,data:KuLWLbHDWs7sb8tweQgYPs7ypDA+aWZSBUM5OL+GczbSqgvt+ebd3RTSn5QolmX0w/hrr72p101WCMr4Ny8v6gTdzL/sA/kgUiEy0YSVq1l+vGydu7bvxbxO6UZNmHpgheSP2M4K3mC4VZDPOPvPQKO1JiOxUwJz8LfDnRuJLylnWof9IP5zMvKziavXavSX,iv:WJG/buxZPwXGPYsjw9JEndb5Y90sbhsl+g2AaRDRMTk=,tag:x2JsK6daV6/4Ntwm5su4aQ==,type:comment]
auth:
    password: ENC[AES256_GCM,data:F5a0+hxcD4A=,iv:DoGxn3scZDsPlH6e5CZprj9eh+PvEzYYYVksUMqfQNU=,tag:i49Z3D3YBeEDsI8aZF2quw==,type:str]
sops:
    lastmodified: "2026-03-12T19:23:47Z"
    mac: ENC[AES256_GCM,data:6B5JHM1oHeo5KtJv26HCsURoDLg1vZ9bubqBRGB58GTDI6fFStqG7DIHkqc+0ayUAn6oG4AGQQ/bTixasuoVf+7uJ3ersdmx53y8PHJLP0D8TUW5zpvR3K0aY8PJtcBir7IRc4lEO+a6FRw/Z6TL6dTQalqxcP4NuVP6t7LgZOE=,iv:pQWjTjmiK3K2YBXQyDM8VGjCquMK0+j7osETHlVlp6k=,tag:kNfDHrU3cL3Y1ZSeAzLPFQ==,type:str]
    pgp:
        - created_at: "2026-03-12T19:23:47Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4Drti3Uh53xz4SAQdAGfep1dT2JfySIA7DfLOeZqKsvkjLf4o1S2yMyBLGVBYw
            haejP+WYro8XhDh9LXgreAsowTRcbA4EzbD554Qbi3O0sRI6yFVetoaC1m4XGUc8
            1GgBCQIQodXERoqZms3QzF+CTDJOdIVZFX3+8fuUSSbydl4w+KqyZclYnqO0F3nS
            7tyLMSiGKS3N0x1l/eZpxgcLiseokBvRhoyShLaUf9mKed4jGwNszIUYriduGT0O
            VCoKnu0pppWKwQ==
            =7Han
            -----END PGP MESSAGE-----
          fp: 8152E60988488774
    unencrypted_suffix: _unencrypted
    version: 3.12.1
