#ENC[AES256_GCM,data:RjZee14zJ7nVpe+mKl5Es9IaoQ==,iv:s+8zb3v7jyTosglvWhUtbttqjEk6b0J1uZxA7Y40Vc4=,tag:kIsSdRPyDA+D+DioytIugA==,type:comment]
sso:
    admin:
        #ENC[AES256_GCM,data:4E4tv7Ahw7Ic0nJ7hD/s54u4xxoSTvPJg7E=,iv:ry++UPvsd/1peiaOj+pY7XIbjUwSORO0njWoGJRmcnA=,tag:3VVAn3tneStfLHtdx+OECQ==,type:comment]
        username: ENC[AES256_GCM,data:/tfmYQ75Np6X,iv:UqGN3UJ/pM4sAgDl442f9mtgOQIAVrGLhY55lPqhP1I=,tag:HeOwF1oe0W6bsAQuTQyYlA==,type:str]
        #ENC[AES256_GCM,data:z5K37wmIKF6NrtcZRBdlYyIybSIuGRNF6TPcCNkH,iv:fQyQoPgxjv+jz/mFpygtaE9ykXZkxtMTA++iXkD0oVc=,tag:YP3IcVmVqBt45GuqcqGVsw==,type:comment]
        name: ENC[AES256_GCM,data:J2ROyI2a2IQuw1JrhoPcPw==,iv:VeSIUa8iSVEtF09dJRoxTuukafncDht08rV+s7xcjsY=,tag:9eDJweOBbfi5otcLXgeltQ==,type:str]
        #ENC[AES256_GCM,data:jUnoHb9vVHBvxncp78oeS9/6qICRN1XdanuwFbEjYysTEIpKECpIShtabk5sBNQ=,iv:1hwi0ChAkXQ1PVMMQfZbIG7ZAS3fxJXnzHoNH7QNmk8=,tag:T+2/GcsRAvo2FBT8Rdv9AA==,type:comment]
        email: ENC[AES256_GCM,data:zV5uCWc6DhcO4CxiFvx2qij85OtAbg==,iv:P5t164awMkKfF7pDOr2oJV95+35eI1zeEEYsRD9fBaQ=,tag:mM+ktNPTZtd0okliFgcBWw==,type:str]
        #ENC[AES256_GCM,data:LHYn5o2f8ixJyHnCqG1X2o2miOVi5mKokGc=,iv:C4NN8aFZl9x2cQeLCurQ2KCs/kQDtXPtgvyLpGgpBZE=,tag:4nzJkSyjyWdVWwPS9OBCwg==,type:comment]
        password: ENC[AES256_GCM,data:J83A76APj32iRXQpVJbZEQJo1gSDzLchBNfsI0ZmO2Y=,iv:mE8rwcWOZKc6U8V9xfMJog04uXS2Hh3poV8lucpObG4=,tag:7BALUNTS6dbezRESnGwYxQ==,type:str]
    grafana:
        #ENC[AES256_GCM,data:Zjnqd2cb/JnGdQqUFDbmcamBosUeZp++pdStdxjsHIVtCrjRMg//n73yxJMX3WN56gZxlFcYcI9h9OdLQm57lvn04CbwRJg=,iv:tkMc6QFtWhAY25JkTIkVJFBCgF1pzH4umpHCxLMBboU=,tag:ivSDPKMNMG/IrdQaHc8TlQ==,type:comment]
        client_id: ENC[AES256_GCM,data:ozSpUNFKWI7vNdRGyja5M+46yqdRSkJYcnAmiQ3qyfQ=,iv:K1C5lu6p6MuR2umeQt06cgRSaBLDjeSWHsEKe9OUIng=,tag:yxt+R+Cg2mlr4YBOIZe9QA==,type:str]
        #ENC[AES256_GCM,data:5D44yj3+kaz6J/PZPhwx56BBjObvAsgX0GwvbLMYwRwWq2qM845nQAKu8DoT/uBczfKnDsQWwwNHA3MloLhyyps33se8f4opu7AS,iv:zAuA5ajP7IhGdtw0ibTc4YSMzdknVJ/im218D9rzk0E=,tag:6/2OpOq8UkeF+h9SqfwJdg==,type:comment]
        client_secret: ENC[AES256_GCM,data:nDe+pc9iqR0XpdzXA5pJN0E/lcqia6ZLONCT1JHHY5Y5kkhnzgn9o33LjNAQbVgn0DMlgqlOMRMvICmXE75eCg==,iv:IhDaJbBFr8YKmNiJ/isrNXoyiPCnhznpkDQF1WfP2xM=,tag:Fv3/4ie8vXpK+Vuhrj8OXQ==,type:str]
sops:
    lastmodified: "2026-04-05T02:27:05Z"
    mac: ENC[AES256_GCM,data:kEC/TghB6Vnk6N3PMyXh+tX2GuvWo08V1yxQQKqU3ssid18IdEz8QhQMtUpOzTg1vWU5JmTHkXreHdC/tjJXRC3T8kt1NHSOwd2mzyzBFRgsfDWQ9SLuivGe7M0K4B1pwfp/grMn7p9XMOPBA6plQMehUPqkonfBhav73YArdFg=,iv:n1Z6vzZzjptphWamqP2SqwxA/5ATrATpJ9C7Q5xP5Ws=,tag:dJEh30WdoBexThxTgm6HRA==,type:str]
    pgp:
        - created_at: "2026-04-05T02:27:05Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4Drti3Uh53xz4SAQdAYo6SFHcpy35UTIfxOJRCPOkQmumyKt6RWkBjjZGu5iww
            j3GSwVXTxZZRzvVjeDaqn/TnEN54/gUzHBVEltWmnMBtWEhMtbnptvB8XD3+uAzb
            1GgBCQIQknyelkmfmQzjvCC67lkXUO2EOooMfomhaMlTNw5GOUjMnTIIy2xku1mv
            ZuXmsWBbr0aFkXx4KDzi10ySDYAD10MheWqT0m1gixbhVrM5tvjPYijH4C4oc+2e
            3c0wATYiSvZvhQ==
            =HvHL
            -----END PGP MESSAGE-----
          fp: 8152E60988488774
    unencrypted_suffix: _unencrypted
    version: 3.12.1
