#ENC[AES256_GCM,data:yS54axgnqw1p4LLaIQFZqZPkEg==,iv:q8vnY6yoMEMDNrPrq9ou4y9RGSsyEjFBM35HjPp+4X4=,tag:+T0Wb1AQGxpp7fTpAoJEBw==,type:comment]
sso:
    admin:
        #ENC[AES256_GCM,data:+GqWTibJTv4HrSMi5ounSgzg+2aiyauyoVg=,iv:Q9UxGuTG6rL+vNdiFCVLKTojd8gQiDzLCIIHpoSj+Z4=,tag:amcORMJvaXXthd+GkiyNIg==,type:comment]
        username: ENC[AES256_GCM,data:H1GuqtsqOkK7,iv:ewwCxdPOyihggMxdxFVEcLZvr4kKs2hPyfZpSs/PCtM=,tag:seBt0plLPJ+GXFyrrvBMsw==,type:str]
        #ENC[AES256_GCM,data:j+mArJHnNS5DU1IAFvMi9DnXgLiDLkOQykGiv043,iv:lScjFnxE/crUbdLLNkLrBMJcfPw7f5fpWEQ++N+/imU=,tag:+ZcNARP/bVM3un2cGBHqVQ==,type:comment]
        name: ENC[AES256_GCM,data:NyNxiFMneggmN2BjOoZCEw==,iv:KayBNVsYVsyvd63HhF3aYZsTryW+soo+WybyTmpDoxk=,tag:YdT7w0AQm6ofy5U525mxBw==,type:str]
        #ENC[AES256_GCM,data:EsC9QBM4VN3mg/zmUtgFsF+LAROhr7O+UtE6sgigepox0eSAbLduTnBzkJIz5Ws=,iv:s74YGMh1n/BVZt6KVsj7J5pk5+TsBlkcffvdqnvfUQo=,tag:NfmeX4ti/jisaclX7XsAdw==,type:comment]
        email: ENC[AES256_GCM,data:tTGrzy4FJ0uItKRPrzpSyc3dJU3ZZg==,iv:ZHiiVOIj97dYRN0BXJPbUP21EEnx0I6yTbgoYPpnI1k=,tag:fs5xUL9Or+AVsLli/nDf2Q==,type:str]
        #ENC[AES256_GCM,data:qDofWPuSU7xYmrrWVzk1jv84olTaSi19qlI=,iv:LTQurh9+E5GovLNAci030c+XBeNcLyGvWKAldVeEajo=,tag:YswLkNrIMxYwHXR32Iet+A==,type:comment]
        password: ENC[AES256_GCM,data:eKI1dUnJ0kpsvrEbW5mFP8ejjMbU1lZXJpFVd47X3vI=,iv:onJSSw1j88ddD2dOtap6B1sT9rAzubBE3oou5oflYiM=,tag:jKdG9uEpz4r7qD0iUC+X5A==,type:str]
    grafana:
        #ENC[AES256_GCM,data:KPz2PxJ9h7o0VJ4OCC6w4RxVIIvm7V0w5MJFqEp2VfjxTl+xwicqv6fYgB158O+uhiBt26PGzq1avQuS9EH1h8drL7iEM+Q=,iv:Xo6yNuFDiU1s5x1gp4e526DfCtJDkMEFdVja7Mgu7zk=,tag:ek+ewUDmuBFhClg/+0XjLQ==,type:comment]
        client_id: ENC[AES256_GCM,data:8vclTL7aQ3Sb+TqEaWx/xYDPXFg1sEmWVoqKeFUSEig=,iv:2zB/A3XFGYEbQ0AurMLKDZ7VUWIeq2xvkNvCUcoPUiM=,tag:ppAAPfP8UzT032eidQme3Q==,type:str]
        #ENC[AES256_GCM,data:7+bij/WaoMXH7aIOCXxmMtrNm0+p3ZBPnYXNERwVChtgAtWRglI4qzrdeKfGlHQBMSvTcDRtMnCrmhtriE9LzwnelUXWw3XwJyAv,iv:WbicHYPxsYuOeQgJ0cgLC6tn91TvTxkNSeMXq/xegOk=,tag:3Yp3KpTzh7RrHzMVQ3NgXw==,type:comment]
        client_secret: ENC[AES256_GCM,data:ssW1YcKHibxyrZsPj48UmAKZ9MEoI3aS+w53C7WYYa1HKuaXYMHKQnIRoWEioMKClibe1ZqxyjrEc29MsHw9yA==,iv:MxtpkNei6pkyNbDAAv6MyGdUTGUWH/vd8InBT1XTyWg=,tag:y/kwPgHUQJ8fs1MP7rxyuA==,type:str]
    argocd:
        #ENC[AES256_GCM,data:7pejEO+ykpBf8ORDD5Qft8NOrLQ1l5ENgFkqESQB/rJT/eitN9LX1wbJ/9bTGXZvkKGtZTKZzHi9b9WIvTMhdJWnhhDFaA==,iv:gljX+xktnwkRRK8+Okm0f+1XOJj87hQgKwW5z9YP7Mg=,tag:+MFHYdDwLTbQM51vHVY5dQ==,type:comment]
        client_id: ENC[AES256_GCM,data:r7f9xdX/GFOeDjCvnyNdlOry1i+2PmHltuDOPrrWhEY=,iv:o7zhRrXnF+3hkrxn8V2zNvAagDWfU6Pmt/CTjcoqkJk=,tag:n6o1AHNpZ+ko8JUFCZSBQQ==,type:str]
        #ENC[AES256_GCM,data:iEmbDzuKcD+aV1KhK2g+zLKO2YoRXWoqqcu0Jo/JMYV3t9vvqj5/9iyE2bI4Rgaob0q9GO2MtjPiEDJrBhn0z99B/PRD20QShUw=,iv:3aaCFKtW/LomoHRgP+Rjha8k6JBD4OcE2OnD2gR36E0=,tag:JFhx7IpINZQDs8O+qPOoRA==,type:comment]
        client_secret: ENC[AES256_GCM,data:ZVz9eUa+SdKhbyVhUzNb9acah7OvdQkpmNKQbDQEMnPTaWTJC+lc4Cr6JRT1ESmXvXHELHioCG2j4jN/2fA=,iv:Myi/ammliz1QdQK+bsTPu56m30q0ICouUH0/+VpuUvk=,tag:iu3qnGMKR8J0u/xJkNNQuA==,type:str]
sops:
    lastmodified: "2026-04-06T03:23:18Z"
    mac: ENC[AES256_GCM,data:lPUHnxz5oVg00XCLMrCuUhZ0pct2UkK4+tRfW86IUx5b2P638ZzwQLBHA2GNcOLDhcg2Eu0bHFQ/zd/H1HYdVhfPXAk3aru58/FDZf906ZBKfU5NpnpianVW8XVFzKUb4ysgrW0cuQNulRmJCEBpMK1U8GYinT582gOOcRXKdZk=,iv:5jsXTTvAED5gLfNIe733x6tPcKCXlmYcAH92SZC7ZTw=,tag:8xH228C6upUvnSzok/nzWQ==,type:str]
    pgp:
        - created_at: "2026-04-06T03:23:18Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4Drti3Uh53xz4SAQdA6WNL+YENKgLLWCqsk9880Fy9RRBihpIEmCL3Sd52Hngw
            q8vqtZEQ5QtEt/LQvX78qLa/mFYXPozY7BriHjszC0A0syBWFj2APmkgjkhucjs3
            1GgBCQIQLL7ipdQIuyEc+TcXiZaVAxHsk6UyJQkxoJXEDuNaOC2aDiiIwKEnJf5r
            OTRGPB5GKVRTkNCu+uaw7DgDIyYa0+hMKA6iXwS6yxOKcIFV0aJFZnDJk2y/zu1c
            daY6vvg3xLwwqQ==
            =C+qu
            -----END PGP MESSAGE-----
          fp: 8152E60988488774
    unencrypted_suffix: _unencrypted
    version: 3.12.1
