#ENC[AES256_GCM,data:D0suKWgQFZ3CV4oV0wJO0tLPiA==,iv:ejb4MA8z2mUsMKJJC5N9DMtmCvk5+1ZkfIPpidh82t0=,tag:5qOSIeYC59tGwaqImLaEVQ==,type:comment]
sso:
    grafana:
        #ENC[AES256_GCM,data:sGR3MIqKKgVM6pcRUFvQQLyk1fzOUbt45beQnIy+TVQSOvDlAX0oEc560YxDhgFN+8YO0hCVNNwkho3uNxhnweTZKIU4lYI=,iv:Ck383JetZs/zA3hyczQyLgZTYFo7200cSRZtgao/kY4=,tag:3YlgWKhVwDFfbsuufaOvMA==,type:comment]
        client_id: ENC[AES256_GCM,data:dqYqNg/zhxpvQHIa7R9fH+/EKqRZi5SejVi07MUtxMw=,iv:3HSGNDjX6GvkXHllX/BcinL0pD1UzxaD5zmPrAno5og=,tag:PXpbE7o84t7RSPgNsgxnfQ==,type:str]
        #ENC[AES256_GCM,data:6/BHpyMB9YWRQf2UDFIV9j326Jyk0+b72BT88mfG4sBe3rkzuXVMIoThE0kt/EFqdrjCC1xnkWRWDUdz7n+DLOiIYpPmeotPenxb,iv:bsBNY84DiPbF45o8SP4m2tWP3Mx0UW/u9Np36vgHql0=,tag:2E9EionLlhP+cKi0QVYZrA==,type:comment]
        client_secret: ENC[AES256_GCM,data:KXbDQAtBRAxJeBucDLn/Fb5I4CSMzcKHxgT12LZvMQ1l6cj12OfvWcCm7zTiyX1WukNM1/Kj9RTFFloCT6REmQ==,iv:lbt2AZwx6dRmvwkOwLMvgxEkZ3t16T0ApZvrEJTOXYU=,tag:2zY2QcYY7QE1ns5rqGC4SA==,type:str]
    admin:
        #ENC[AES256_GCM,data:4DqYp4CZWG/ynPRGApJkAo17nWE=,iv:Jd4UaW3vVsDr0EWeVD/JS4sJxmF95LtQiMcXO25mibk=,tag:x+X9BhXE0H0kJ50e4rdm0A==,type:comment]
        email: ENC[AES256_GCM,data:y7Fr2HEhcwQQqnYe7vVcJ99Bzce+hg==,iv:ZUReecKqaOfEjBwqZmzO7dFEW2bX2UlB2VPS5l8uJig=,tag:X0e6OBViZ9nZ9cCLtc9e7g==,type:str]
        #ENC[AES256_GCM,data:PKj3B5FhxRtjtBr7S2/4Y+fqTHKGds4=,iv:pmAx/NIVyV00mmLcLAN1tABhPYrzHBV4wdh2ByL2ttw=,tag:zW8+bVBiTmTHdjdQDHy/Lw==,type:comment]
        password: ENC[AES256_GCM,data:902CbVmKcwThQpqQFz3qixKXokU=,iv:37oK2zoeoJWk4OdLuvqqSoWEaOf/DjlQIM8TXR1PvM8=,tag:WrOY3gKOYeYacU2ftix27w==,type:str]
sops:
    lastmodified: "2026-04-02T05:47:20Z"
    mac: ENC[AES256_GCM,data:rasSCwIKekIIIbOBKVzYALVrSEWOPEdsKVQernstRu+J956vI5F07fMMDKl+qbbioZhVnCWtoSgI7mW3LJrbXIwvSZT+j+xEeu3zIgmLGY1ybeH6WouANq4l/ncLr/QHf1bL/fsDYapIKlmWZftc+dqH4UvSO4sh1LoLJn+tEs0=,iv:jqG59c+xe+8tg6qSjEamXldoxWIseBczryF37LsAlzM=,tag:tewHB/+JGFnOM+/SJxpsDw==,type:str]
    pgp:
        - created_at: "2026-04-02T05:47:20Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4Drti3Uh53xz4SAQdAq289gN0VcJudAOlVaNlBrfA5cydhS2dJy3x9b31GCzkw
            xiyWDWsPHL+BACuJbt+zINqwq1ATrve0CEIuZSkpwszldVjDnzk9HOohSyDDl4oX
            1GgBCQIQppU7NJi0/PxKeFfzmD6ZttzHryDhiyBIqwvCyTJed4jj2Sc/UvnG6NH+
            kq7hphzyObGWInuZ/oXERNo+OpOaUktfaJjehA27mxKCFuSu4DSOHOygupG+btR3
            2vRr499ItFA2JA==
            =4kFY
            -----END PGP MESSAGE-----
          fp: 8152E60988488774
    unencrypted_suffix: _unencrypted
    version: 3.12.1
