#ENC[AES256_GCM,data:d8m3UWdf+QyfFgeR2hJDLdxOoNC2ldSk15b4DMXGWawDkClEX0I5gwtrNIJ/ZKJej1WKaTpH/rVvq9QM1BaZGa5pvu4I9r31Vbrf,iv:B6u14pG1fMAEhD81ngJG6UgPwA3WmejGWWUvRz3fW9Q=,tag:AkN01YlsXunlXnI/IQsT1A==,type:comment]
#ENC[AES256_GCM,data:WV0jws6HUKpVNW2GD0LnMcSoyOMDOPoknEwPY/ldY4Y9xMGcHo2Z3IMszdljFfwG33XOwN8s2JngO1H4NYnDZIYINHt4X9eJMoEDWWw=,iv:HFgtI3MsvcoyEbVuadHVrSiTySYyQbr5+o/dPpuAXgA=,tag:oJzHDM9dFXv9ZWc6nUklRQ==,type:comment]
configuration:
    backupStorageLocation:
        - name: ENC[AES256_GCM,data:0YBiMF/vIw==,iv:e2SU3hVlg0JROXH6rJzXP2HyuJ3HY4Ikmg8h5bQo17c=,tag:5fHWLdocxVtd/RU2Z4eOkw==,type:str]
          provider: ENC[AES256_GCM,data:znDG,iv:K/1dVZlHAEjaa8yulY5IbmQ28cX09elkCmDoDo/a6H8=,tag:13d2c7mV45C4Qvkuqp6gPQ==,type:str]
          bucket: ENC[AES256_GCM,data:OhmeEdl2NUg8aYhyIqReyHoV1Q==,iv:vcEHgDQA9rQBp9Rn6QWMY3chcgPYeKh/gL42ZWWHFDY=,tag:BldzKLvlMAqTgDiAGqNRMQ==,type:str]
          prefix: ENC[AES256_GCM,data:99G94FNA,iv:tqsjRHVS4OhACnbXpSe87N0LTfegrC4P0gCt6n49kdA=,tag:K3jqnkiNwuTt8WSFnG4Qwg==,type:str]
          credential:
            name: ENC[AES256_GCM,data:CykPBdsb,iv:euY9uWYmDS0aKnMziqYV3xNRQgI5kJWc1qvP0syUbiY=,tag:lW+2a6udTYljVAv3MES+mg==,type:str]
            key: ENC[AES256_GCM,data:9SkBrkA=,iv:nA65kzDCYjr5P6cB1jqzuFPnS1TqMfnXBjraeUgDWME=,tag:YDIpBHXNIH1iSy2s41yiVg==,type:str]
          config:
            region: ENC[AES256_GCM,data:4v53cA==,iv:Dmr0j5TcHAD4K3YiY4QCMXNuEKgF+PFgATlgUa05E70=,tag:A+wUmpFqLYCMwOwpEslWNQ==,type:str]
            s3ForcePathStyle: ENC[AES256_GCM,data:4b7gLg==,iv:m9XzHgtmiqdYkRseGoEP55uocC7890Qlij0zsVp6iCs=,tag:hFchTQZUsLimO6uOHbJylQ==,type:str]
            s3Url: ENC[AES256_GCM,data:DKoY2K9yrh0ztHBXutaXSVPCtY3y6JlDkGHy8zb4J6LwjvQELRC3PfdFIOyNNYXpvm12/lu+C0DQi1Ane1SJC7c=,iv:PnpfkPK3nmrCE3IOVmDtU2AZxP5Tnup0X21gQpPTH1w=,tag:VFqTVeW9nFVNpSZihJBeJQ==,type:str]
credentials:
    secretContents:
        cloud: ENC[AES256_GCM,data:SOy4bfRqXJLocT97is6/iwqzjRZP5RVN/mqLSyFFI+SQ3SmEJnkfteOCR+pfErfNHVQz0piv5KrcyrbOns2ixTEpP7Jw9eTjVYT0L1OePC9iCTZVDI5Xmwj9JRr3yEqMjp0dv1krx2qu0/BxkCE/qdr1hiFPSHCNrXZk8QEa72BKtamblbPlbTy+GI/Yeq2svb7gBQ==,iv:x0jUzMU4I3ukLlt/Y82cYVppkNi8fRtuSdSP0uPA/es=,tag:xcq09/xXk2P5DyZ+IigV9Q==,type:str]
sops:
    lastmodified: "2026-06-07T02:55:47Z"
    mac: ENC[AES256_GCM,data:8NMqRKvlEi3G4aSytboEXhpmb8tz+faO2gkMVslDf9yN7eHqNQlrEs/hsbbVIpe8h8bzqiNF+HWOw19FPioreljYmFGQE2SSURUap49EItoZRoXAefSuos01beSKCL5gdI8moWvdlgSWIimRD0i0YUSRNOnEwVMR7mVYjvyvc/s=,iv:BLKBXJjB5egVXhkO2DNugk5jJG48tz3R0Lv6vwbyo9g=,tag:r6LqKkfFvvLZrrHXyrsWPg==,type:str]
    pgp:
        - created_at: "2026-06-07T02:55:47Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4Drti3Uh53xz4SAQdAGSWrmnvXQFRg6tkjdiWH5GOxuJIEH6kXtoXmSQ37MSEw
            7vTQTKqDJSR7UfY1vDDNHhR9rtaxYKB0fCl2gqO2+pL4ZdwzIWERf5mMItZWkqvK
            1GgBCQIQd1RfR+zEDrvEEJFRXsMYf7I7dxGhnEYdhtdWoKtEndMgmu3moIjs5e9+
            LWzAoPy5Hrh8MsJiKjfL7M1AQqQZIE7ivwNpUpztnH9I7eCqan2D4OGSDZgUaDum
            I7wvTAXWOFlHAA==
            =7tCS
            -----END PGP MESSAGE-----
          fp: 8152E60988488774
    unencrypted_suffix: _unencrypted
    version: 3.12.1
