#ENC[AES256_GCM,data:ZN9LN3gW7jhlXHLG3EZ6,iv:Kj6YtT82+WKCUIwOqy8MVLdfr0Ubq7EivCRwaaPycXs=,tag:MAVo45njdQxYLmK/0tFXKw==,type:comment]
velero:
    bucket: ENC[AES256_GCM,data:9yx1Ll1UceSUgNtY0C6hdiuKfw==,iv:BxOjzN1RANbteI802I+jOonmX/Vlc17LOAYf0RrLrAk=,tag:MxBXl53iTKKQkKvL3DvLcA==,type:str]
    s3Url: ENC[AES256_GCM,data:P4eYZ45JvuooC0GsG7sfoIlGnDBQYoV+mg99rSWYXPm8ba81/0eacTWeAmd3aiJkVgBzBvxttCRrDGSWmhYi8VI=,iv:BnbVqw8dv5AtsA3zasbcBjvLm72uxSzOrGahMy5l3NM=,tag:hT8iDZq6x/jKbrDAi9bkaw==,type:str]
    accessKeyId: ENC[AES256_GCM,data:5vBoQ972UnW5lkfRZ3uS8bYdG6mOuIZ9FHrQ950DFsU=,iv:iZjV/V6cU7vxL5eUQ8bQ1amXwbjaIyFsjQPJ34Ej3T0=,tag:i/9yWtWGwwIVvz/hXuurrQ==,type:str]
    secretAccessKey: ENC[AES256_GCM,data:WceG8XwRp1K5mmZ6P+aZnpH/ZlzlxPur2aG5GOWswbRLblAphoqG4ReEY0pZBC5z1w9GiaW0DNB1+mNnS0wHFA==,iv:tFAPllYmEazX9fqupd79r06RXcJsQyBUDX9tDfMBsBo=,tag:uI0xaO18obHN10N+i7dFOQ==,type:str]
sops:
    lastmodified: "2026-06-02T03:30:57Z"
    mac: ENC[AES256_GCM,data:vN1W76/m9yUs26To0zZor5J+vk9KuV83YGbYFH9KkEFJxmc53BC59kVmBiC1/4wUds6yTHXxN5AI3LeSq2NrddjzdofodMZY828ltQZ9ouO95IgPX5mMI9pIEN0dwDkwCMblBFCpbOrUfbbx/WYiJtoRAso3MBBYC0SbJSQR23U=,iv:unfpGsqqyRbuXUUH88puLGtTwOvUgp0x6J6QAmJVSbE=,tag:WgLu+e7bQxTj0it61QbA5w==,type:str]
    pgp:
        - created_at: "2026-06-02T03:30:57Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4Drti3Uh53xz4SAQdAO5FnkXSCLNKRNthWv773lGWo3uQhk1XknzG7GvmXfgYw
            oOej7YNu22wkx6pxpydkOJccw29EvNXlMQTsVAhFiUzBvXxpASxUqj5tBa3leqzz
            1GYBCQIQjXnNgdUlAIJTE7z2s4xSOtOCyxKt1iO+LwMCK0k/6vy2vhPe/DV5i3mx
            8bkf5UeZRMG3UBltrcUqTJh09Of05i1MX3iK4OlzGzqgrx/A3RVKK//HCN1+/vSb
            k3GUA7oUr7Q=
            =zUxT
            -----END PGP MESSAGE-----
          fp: 8152E60988488774
    unencrypted_suffix: _unencrypted
    version: 3.12.1
