{{- if .Values.secret.apiKey }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name | default "cloudflare-api-key" }}
  namespace: cert-manager-system
type: Opaque
stringData:
  apiKey: {{ .Values.secret.apiKey }}
  email: {{ .Values.secret.email }}
{{- end }}
