apiVersion: v1
kind: Secret
metadata:
  name: grafana-sso-credentials
  namespace: auth-system
type: Opaque
stringData:
  GRAFANA_CLIENT_ID: "{{ .Values.sso.grafana.client_id }}"
  GRAFANA_CLIENT_SECRET: "{{ .Values.sso.grafana.client_secret }}"
  HOMELAB_ADMIN_EMAIL: "{{ .Values.authentik.admin.email }}"
  HOMELAB_ADMIN_PASSWORD: "{{ .Values.authentik.admin.password }}"
  SHARED_SSO_ADMIN_EMAIL: "{{ .Values.sso.admin.email }}"
  SHARED_SSO_ADMIN_PASSWORD: "{{ .Values.sso.admin.password }}"
