apiVersion: v1
kind: Secret
metadata:
  name: authentik-initial-config-secrets
  namespace: auth-system
type: Opaque
stringData:
  GRAFANA_CLIENT_ID: "{{ .Values.sso.grafana.client_id }}"
  GRAFANA_CLIENT_SECRET: "{{ .Values.sso.grafana.client_secret }}"
  ARGOCD_CLIENT_ID: "{{ .Values.sso.argocd.client_id }}"
  ARGOCD_CLIENT_SECRET: "{{ .Values.sso.argocd.client_secret }}"
  HOMELAB_ADMIN_USERNAME: "{{ .Values.sso.admin.username }}"
  HOMELAB_ADMIN_NAME: "{{ .Values.sso.admin.name }}"
  HOMELAB_ADMIN_EMAIL: "{{ .Values.sso.admin.email }}"
  HOMELAB_ADMIN_PASSWORD: "{{ .Values.sso.admin.password }}"
