---
collections:
  - name: ansible.posix
  - name: kubernetes.core
  - name: ansible.utils
  - name: https://github.com/k3s-io/k3s-ansible.git
    type: git
    version: e9e0978a47fa6ecb6cde58bf30bb461e1f6eb4dc
