#ENC[AES256_GCM,data:emdYKCJV21ORK5mqh+UVFXkQp1PsYBSYp3XTgejrLueNw6+1+Wq6/FrjMUcNU95vsOVa3xc8587p8dIAsYzofYmx+HbhJSacYI8bfUFgOOLVe6YLc2TRNaok0G1csMHBmk6WmtY2C7Yjul5PQFNp9F45pZ1wDTXYgM1A1khm21n9YF/OhFs9J6cK0H2WKt5idXk+sL2Jqhos+A==,iv:1eN8K6TedbonPYR5mSvyUwnFYm1uhSMZqB5dVKLssm4=,tag:MIt5gzbBxSr12kKUhy66Zw==,type:comment]
authentik:
    secret_key: ENC[AES256_GCM,data:HRi6DKfbXAo=,iv:ysL2y6F9/Z5xBBrSffwqGd/YdeJr36d5btWX/NgFyMM=,tag:xEKSEaZY5KetBR0a3RhNRg==,type:str]
    email:
        password: ""
redisexternal:
    #ENC[AES256_GCM,data:iCzkEa3i4eMkWoiBV1nrN6nZ4KOdj9WHQAYfaHgdvQ==,iv:ClC64AyUCzebv0T6yQIn+RNa+b3MyMx7W7TvahU6lOk=,tag:pzkFEwSfz+TqnrKdmzBPEg==,type:comment]
    password: ENC[AES256_GCM,data:2C9jdr0Ls48=,iv:4QWHL1XGv6Gt9p2GHZKSI8Zs4QpkF+QukEnvpneeM3Q=,tag:0ii8eCKfD8ZSoRNl0SZCOA==,type:str]
postgres:
    #ENC[AES256_GCM,data:yp4kkYqdD5joF+WOayqFCDr7ljWMvqYeaRQgQQtpjTtdN2zm,iv:B6Ym0IM+1IU3Im73ZTJWWTsNeMleWzEhlnKJFAH19/0=,tag:S18EU0CJ8LidlW4e7GgsXA==,type:comment]
    password: ENC[AES256_GCM,data:XAqeOsfFwDs=,iv:wFH22ojUuNwArY3mdnGp4bdIY9xAu0eTtYN0OSnMGsg=,tag:o2uBGZP6bu3hL8KX/TqhZA==,type:str]
sops:
    lastmodified: "2026-06-07T05:50:50Z"
    mac: ENC[AES256_GCM,data:Hh6OVSk/CsIu8+TRA//K90VkWQuP7jsFrQ7x5AKIG9afr1c4VntuMSzPTBPaOtTubSdcYFOo4c+wrdsuomsvPJcMrj7pIJC9ySJ3xSj8XsKwVEER8e4ec4QLTJWZAUuZhDuNgeLeoGfpz3dFzVwYX7MjUakvOBn6sgJjFgMyyLs=,iv:LoSDjAL7awPFyqKjGhT/KBmYRA3uHX7IJmWQfR0Tz9U=,tag:1jOWejaDW9ziedF/4BDSgw==,type:str]
    pgp:
        - created_at: "2026-06-07T05:50:50Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4Drti3Uh53xz4SAQdAPhFC7PKTbl/d9ebnpv57LRMUEfbRADPT1oN5PnaPH0ow
            1btDJ4JPgi/RiDoNwfofgbVZXkzRfHeDG0R9bB+yBqspkmYu+fhHeb9TrBLr7yF6
            1GgBCQIQTVWAhjt4l3KOY+7dkrGwm6YyoxBGuYoUCvF+8bcKYIuKr9eFLCh8TgjV
            L+wr1sE6dDq1p3LQAKIUSCLFiacgvGszn1IbjC3n5/ZC3i2B4wkC+dETXSnsXjXO
            o0x5mxgVePfzDQ==
            =Uv0u
            -----END PGP MESSAGE-----
          fp: 8152E60988488774
    unencrypted_suffix: _unencrypted
    version: 3.12.1
