#ENC[AES256_GCM,data:h/HHbbCoqVV1VcD/M4H+UzwuSJv+sXHryIOJhZ187uXliUgf0gy6zxnRsW7CXeu3UXbHRuFFnE6ymhcQYAvBO6LcMA9Gkj4YKenZ3h4hyficBCKE7f4/HHUB0sISgoNnedlh0ZAy2gBTd/DuffTsAD7/gYSnqVE2XCr6ejNr1onjMKkFd3JPAXodc8JYJqFHoD3cGdXhwhOyvw==,iv:Lco9HFu3EEOVHHE7dE5UYvFhSqfNRAPsui2qxRpsxeY=,tag:fACtMIjFh/3FIRt6rSJwOA==,type:comment]
authentik:
    secret_key: ENC[AES256_GCM,data:06ZrnQAhmD0=,iv:JFriw55KoGJ2Qkd+Gm4++wWNmjzRZmmt+/xc6XROI4M=,tag:BGzkjw6HKsiPGgYMoG0HPw==,type:str]
    email:
        password: ""
redisexternal:
    #ENC[AES256_GCM,data:WLWYNzZb7hrDGCBonX3I72kPKlOiEJvb/nJpHv5spw==,iv:rYZlXys5H+1xthpJiC6ZVS82gNOF37QOmERLk6fTbs8=,tag:YhhMFdg12byjmObdWGW9Pg==,type:comment]
    password: ENC[AES256_GCM,data:o2avdVUtSrY=,iv:sMOhL34Vir+vW29uM8F5D9JjKodHH1VnQnplwIhB9vk=,tag:tgtJwLwA8aCKcdr0a64zng==,type:str]
postgres:
    #ENC[AES256_GCM,data:TeE97VzORe17JXMCqO+R0JQP6G0fM+mDTB/HPcdJV26smzv/,iv:1Kkk/UoSjdAvvXviYnmLlZu39ItYH43YjqybcSo5lNo=,tag:BXeyJD96yvS0UC5y0WnChQ==,type:comment]
    password: ENC[AES256_GCM,data:15IO+Kr8NLQ=,iv:0HuNNl/oXvhabrrtXwuAkumuNoBjMlnOv4IQ61icSyE=,tag:yg8fwoRH6xkDAAUL9oYc8w==,type:str]
sops:
    lastmodified: "2026-04-02T05:48:34Z"
    mac: ENC[AES256_GCM,data:lTe/vhUbULdIHCY+bIZBJhhZEbCjbLcwWSimygXDP+YmsfOgYpXugprpUf4F2xSNrKbk/xLtGnDEXLmidjgXceH/LF1ne44wb7A3RohH9Rp/0BTksgWjsLocqPGEH4Zm2Go4QdOUYKAPaAmdyYNMRub48GLUXW5ClfTUoFQqwEU=,iv:Ka/jKLitObhBTGIoss8sT8wfsWeW73aHw4oRQ8vDbpU=,tag:t1yPBXS55EjqVOQWklYJ3A==,type:str]
    pgp:
        - created_at: "2026-04-02T05:48:34Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4Drti3Uh53xz4SAQdAJ12Bp5EDLBMfLELGmZeUN2YN3NGlKgQ1q7z1DfH5T0Uw
            BcbCGvrGWph/NWnfhOMMKAdAotD6h6BFGE8/WNDIxl2O2XgqljbgaArU9xYU4T15
            1GgBCQIQp5oDuh94SRoqWPuwhy+mkVkVBxvQDEz2EeHmRkj/yFEVTn9dGYjfc9jN
            VsSmQryVhoG1m2tw0LxYH4xIPiGG7JZjQTKxrpwlr6f27qspwqwkBjt46qHbR1iT
            4tMZ6EjmY8YD3g==
            =uRr3
            -----END PGP MESSAGE-----
          fp: 8152E60988488774
    unencrypted_suffix: _unencrypted
    version: 3.12.1
