#ENC[AES256_GCM,data:nvAIh9pX6fUAky2VKxKCDhUdLdQ6TJUuG78bFOW+5vVCKEbTXZg5CxdjmhmlUcZAMONrIfDxpQQgvTDon0ZPbL+Fk0YV4j0WyELsC8uZEuK8OObObq8BB/M09ulBO1qvIYFCOnCpHmEseiSEDodLMlHEuw7sqD8D0ygajFvOiEw6/XndI3x6fW8UCfsmcI24utPQSU34HdNtlA==,iv:CJwPSaX+YSixWI7PO9v1WkRFDufHzOgTG0jBIUHczYU=,tag:8ETpBVSKcsNVSLOmTSJ+4w==,type:comment]
authentik:
    secret_key: ENC[AES256_GCM,data:MBPhm2zF5a8=,iv:BpQbIDnl/5OxJ5MWyg5RBZDFpwIGP9eV8oDCM2EKN7o=,tag:HbcA89HEvL06/l51aGc3iw==,type:str]
    email:
        password: ""
redisexternal:
    #ENC[AES256_GCM,data:KmkWPshgaHYPdGpvLu7jKQMzQRYeei/Arpf1ymxvqw==,iv:BfsynnNppThLxugVepuUxUgEJtK0B6B7eEcls8y1Vyk=,tag:r+uymg0cy351sbuSS2mDaw==,type:comment]
    password: ENC[AES256_GCM,data:jv+n0KEM0KU=,iv:3qcsjQIW5V24voORsJkNddrcCbu/8uMtjIxi5JA3Q+8=,tag:PqHXIuRkXV0pV6UxqWgt3A==,type:str]
postgres:
    #ENC[AES256_GCM,data:Rqwwi6/lV0ZNYwX8aw069/JJwulw33LqyQUmom7boi2teYhc,iv:Zy0v37TV5zwNxsp2fW+wt2iAbb61GNL8LWEDnyLAR5Y=,tag:YjC6olKZiuzPhj8g/VwcsA==,type:comment]
    password: ENC[AES256_GCM,data:mbxvELwFcXM=,iv:KXLN5x0dy3ZRv3rhzlvH9vXKT5PfN6BG41PAH2iu2X0=,tag:FPLTDYJeTPopFObmcdnIMQ==,type:str]
sops:
    lastmodified: "2026-03-12T19:23:34Z"
    mac: ENC[AES256_GCM,data:s5QBz6pAOjOekyTAYeLwAQjpOuyV6ZwOEnlppd4XDd7q4K86xpE5EEg3tDbA9ZWgifeW3JNPgQWHBuFxmRKwvAH6HGAQqoxLg1wWvYXUflc6tc3EVLiJS8QoX5KpciU9eKPasOfkCMYK8dbQpLd9lINnCWC1s8+K2ec6Ct2joa4=,iv:P1syDTnFPGL6Q4psmV4kqf9Xk14QikrkmJPIlx1mjoM=,tag:rcuUGopaxfE8qe5E3afnlg==,type:str]
    pgp:
        - created_at: "2026-03-12T19:23:34Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4Drti3Uh53xz4SAQdAWQtIUPDYm/2344cPtdmlroUL4/B8RayioR0GmBF49QEw
            36XXNTrOYivp7DBaAMedU03WkZtyO5rrFvPh8GP8cdj0S+SduCzGZVnIfsa5Fc3Q
            1GgBCQIQ0KjwcQ4U6/u6IQNzw7eYJeGzeBM49xvZezmf2BYO1m8b27Y1+XmZkMJu
            yi+VrOFD4RqLnSXidQFUoLZRFdyIN2GYXm/4gjTO9MjcjoocvWVIugbTfNc3tJvR
            f97/ZQDbyvfiWQ==
            =wkPp
            -----END PGP MESSAGE-----
          fp: 8152E60988488774
    unencrypted_suffix: _unencrypted
    version: 3.12.1
