adminPassword: ENC[AES256_GCM,data:fkCzy2OFr0c0rh/wjkeHvpq7WZob9qT56+xN6NyF4za+TAUr1eViZ/Tx,iv:8ZbGdwmHxhkUP/RpntN6q/bOWfsYeViKWxpFhxlDf6A=,tag:uwnOgxgpD3Tna7oVqBirGg==,type:str]
sops:
    lastmodified: "2026-06-07T05:50:50Z"
    mac: ENC[AES256_GCM,data:rmh74QPSkR/j0M2DzDGq1gnAuJel8nypBS6WRKrhfgfJ00XjiR5/mMo1PCWQ4oMkNIm9ba8BdBeJZ3a/z+J4UC/QCfkxC4VRy/6DB6Mf5wmj3la4wyTDwa5lVBpZ+7EaZ36iKj440anGPbuFPvjW8GpaU/kCqUAoLMZ4LHrwhsU=,iv:txAtszE/5BihL4Hl6WTFPwCSJhz3ytqArL4+65r7hCs=,tag:/EZ8swFaXxf/Bg6PhrChlA==,type:str]
    pgp:
        - created_at: "2026-06-07T05:50:50Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4Drti3Uh53xz4SAQdA2jDbeIpUDx2TmO0mnWxHoBsBv+P1WR/gVGdCd1YuCjkw
            kNrH3iSyyA5nxQgbH18Ue4iU/n9mYAlG3hYraGTXJvlN7mmMQuh0Gsg8wD3qIvp+
            1GgBCQIQhqjvXtGqITjBLS0UGH0lpClfmp3pdWzKB+T30GbLKFJW+G4yd3tmQtM3
            vRgdv18WBeo+FG79e6zf206E6LITGtNmUUjlDrYBG1UWIFJeRWxEgnlDNv8xK5Pc
            OQs538trNEUqzw==
            =/bjx
            -----END PGP MESSAGE-----
          fp: 8152E60988488774
    unencrypted_suffix: _unencrypted
    version: 3.12.1
