adminPassword: ENC[AES256_GCM,data:z/QEwqS+5SipQB5ztEVJYQmMeINgCxYHcdsHaZHbmkwcLKQIwloW0uD/,iv:nIVS9TK0V2TMdBO1wQBAvSP6K81WtcPYWsE+r9YkxR0=,tag:HSE8NkHLXtTQQsTlOCu41A==,type:str]
sops:
    lastmodified: "2026-03-12T23:59:35Z"
    mac: ENC[AES256_GCM,data:GuToERhSYc/0/i83Jr0SVh6lcyrVojSGfEunoBHV/FEpoTuNCw4+osYV7DUDfbiBAl5+YKmX68nYT+L35o4e/jp1aYh/Kg/3VrSlJ4vUiXepUECAvd0MaU/zjUqNmvtgf0oTXAU+dSX3H8w/AzRVYbWkz6DCuHtZgKK4k0AHw+U=,iv:i/PQmrweisn/dGRNLIdolCwirM1uvOBQuQRuaz67Ayo=,tag:y063QdD2sqG2WEQF4tqvVg==,type:str]
    pgp:
        - created_at: "2026-03-12T23:59:35Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4Drti3Uh53xz4SAQdAjX5NIGlSC1lmyM/YQ74/Wlez/S/M5q1mjYB/pdd5wQUw
            KU8p9j1Sjjb4NMc60XdNnflJvnQ1K8YeJfba1YRHN8tHUHOeJZGSsITT//fvOZ5O
            1GgBCQIQ2rhOalm8UkXgh83r3RPKOAQ6fpT54aR0U30Gw9tieURCDSsOuCu1sFO5
            DQE1aPWGrMcr47Aqp5UyzpPPAGEoXG4CyZecUEsgL1m3ODFGHyfwSWuNlXHDltdY
            3s/t9gxQCm7u3Q==
            =kE8Y
            -----END PGP MESSAGE-----
          fp: 8152E60988488774
    unencrypted_suffix: _unencrypted
    version: 3.12.1
