grafanaAdminPassword: ENC[AES256_GCM,data:EQEjpK/L5W+YsjtpfU3pHVh5/rc=,iv:7+td7nS+qpGJ5wq+wZOUreLcEgeCp3rCkknChfCbtOY=,tag:c9auc0xSM6LDxzoKFEp91A==,type:str]
grafanaSecretKey: ENC[AES256_GCM,data:M/mLvD8ZqY6QMICSJLWTNRJ36GfP,iv:Ya8LbQjKoYlkymuWt+mRxtAuW62yeiQUG1FFXVnOQSw=,tag:K0TObAlvSgaj6ExZYPNP7A==,type:str]
sops:
    lastmodified: "2026-03-10T05:07:13Z"
    mac: ENC[AES256_GCM,data:TBt68OJjUwhyPHIMayu5Mwo2vw0aT+wN7CIPutqtU2gWvcTE6rupZk2593HTorgvekJ50r1qOHjr0P51/D91S5KdnLsPW045773O7+OjEDn+rFMWF5AKKB1I8lFIjCnqBwV/wTKKEtJjVUDNI4AWkkfcaySBXLd0yxeR18GH2f0=,iv:uA5BUe5Q7sexRip+mmqZJDNbHgGjBon6BdC5X1y81to=,tag:dW83Cj/jiSRiu4J2z8jb5w==,type:str]
    pgp:
        - created_at: "2026-03-10T05:07:13Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4Drti3Uh53xz4SAQdARPud36TRA1BMBx8hVYxvdLgSk/Mr0VNe8/D2ULvIlkEw
            GKX7TLxrPWAcfGIzK2bNJoWHFwDEEDwc1Em6NWQDqDtNSEPovDZDm5A2Rdg+wu5g
            1GgBCQIQsW9XFVWsQ4JHXHv4ct4pYzYYSUHrkpe8LkvuVeultPinEpD5PwMjd1WJ
            tiyYXNE8k/6aX5I+D9/mML1TMMP7h8tK2bvLFUkNBCfUzFRxjdsCKXkP9CepDx70
            tU2mytzspJWMBA==
            =dIIn
            -----END PGP MESSAGE-----
          fp: 8152E60988488774
    unencrypted_suffix: _unencrypted
    version: 3.12.1
