#ENC[AES256_GCM,data:DYWit14kuyCJkRNWuVBMBg==,iv:5G5Gbj6B+JnjAvqtqwk8EWX8Bmlvnon4M9cmSutY/r0=,tag:PivXFY5di1n8LD3MzIE8Mw==,type:comment]
#ENC[AES256_GCM,data:N/ubsyEtz7lGk1lGk0zOf7JbzdZzf13lIDSEIiYPESGlLQ==,iv:9f1ZOYylXkmEWLWnyujBEMk70+FM7xQe3EQvw8Fizn0=,tag:afuP13jmIX93Oy1Y+9aqlA==,type:comment]
#ENC[AES256_GCM,data:9dVIc41dGT6/O9ojKH2vD8PHypuB8eNbb+1RSqbY33dpQ1zJ4odLZIseeIZ63Biz3/SdOSRTEA==,iv:Fv16B5aIVmJ6pXR64KVABpSEX9PlTlK/EMmO3LkiWlo=,tag:0/TC6N/CGSFdgOBKPbC/6w==,type:comment]
openbao:
    #ENC[AES256_GCM,data:WS4Z4uUNuy+YZyD2gmrBy4GV0trLN+UPjhdsU3mAzyIZgxU=,iv:fNDCoVl6bw7JDOY5W/ZKGO68tr6IJ971GK8C2aNK00Q=,tag:9QmZ3RnPNm4tNWqyypwihQ==,type:comment]
    rootToken: ENC[AES256_GCM,data:eFR16w==,iv:4yA8CehhYG7s7qsTLDxzjXh82lb4rhIAIoQlX8QWl/I=,tag:7m6lMrxvhAGX58dXxHqnNA==,type:str]
    #ENC[AES256_GCM,data:A0ioBq5JotsS1Q3TrjxMY5RK+seV9aaLHVGUl4J3MRb2EzOhWNJAECKwMt8p9wN/8tsNIF7CFxv2adY0vzMMruvgkM6F,iv:iQJ9cQ5uB3mHeUisnItrebgAHLy9veHQbDEPa5UXDZk=,tag:sIydcobSHmcBGUUMCN+OdA==,type:comment]
    esoToken: ENC[AES256_GCM,data:CmnWb9Fp,iv:U2iJeBzfCfJZKSFsKKmViKNNLPV/CMqDhaXWNPsqdOE=,tag:dFt/LmyjFCxt0sG7n6uxow==,type:str]
sops:
    lastmodified: "2026-06-07T05:50:50Z"
    mac: ENC[AES256_GCM,data:xQs7MgSh+5d9Ab/RLNBaO3jdnzIlEF1503rAzQyphz4gUwxYrREVcSPi5NYMltAp23Dqb3ArQwcRiPhXUuVvmiaH8W2Xr/7x9M4xdqVVMeNlN/HJvAUtAetJqzzob/26dwhnw1oFkawc/OTMznGid3Ex0i+Wltk2m+XVf0filsE=,iv:lmsZhQGqrAhcvm5M+g0ctTcCeDnCd10AVz2PJBKyz2c=,tag:aTZIb+JI17jJPkgfFaK+iQ==,type:str]
    pgp:
        - created_at: "2026-06-07T05:50:50Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4Drti3Uh53xz4SAQdACIS8xqnsSPZb66NR+G91zYWamXTjlzk2eNywNbARC0kw
            oQDUlPo7FvLhHexIliVyhJ7dZBrSijB67BgeMX6guB/CEFbeSw0Xr91QtFYucmeV
            1GYBCQIQPMQL86t4xWnl4+L4iH2B482LUgs3SgpYiHJVvpqlMNfciQQZDDAonnLT
            zreC3sK0aRcmOb3SM193eR+vOjpN7l5OvoGxCcN9xvSCB+3EAsMuDE8XIPtk1lRm
            chRibw8rxMI=
            =hxwC
            -----END PGP MESSAGE-----
          fp: 8152E60988488774
    unencrypted_suffix: _unencrypted
    version: 3.12.1
