#ENC[AES256_GCM,data:dDogDqLGPKG1fzXfr8ai/M1lREBq37cMBMsyVDIAoPnmkMKe7G4MEkukKLjZ2VN8naNugiegdGTU6htJOh+EyPTUBsloEmym5hklHQhhLEoYIJgIgp/Y+ixbDunrXMVgst5fEQ657c5BgqjGzKDYCZUkm01SnOtgEC3jEqWQAhQE9e6T9NX+ZwCfS823hFfgDBzwtCird4pKXTIEig==,iv:2CBMJ16gtW1dvA0VmzJyGaK0rMUPwdj7c6s36HzRQ5U=,tag:j4Is/k7mcWmqzu1+DDiJxg==,type:comment]
auth:
    postgresPassword: ENC[AES256_GCM,data:nssz3JHcn6c=,iv:AT8OjJczkgcil5mwDnSxWQGqQR4M+Nsz6CyQgzmQ+lk=,tag:UyuoZmiD7ebQHXQeMAPfzw==,type:str]
    password: ENC[AES256_GCM,data:+/m6OgH5oVY=,iv:TyaD8GPtr070jrB6Q3Pw3c3zlFpG2Rt3RGulJZrzoS0=,tag:XcC79Mgnp3pjoZNSIDKUZg==,type:str]
sops:
    lastmodified: "2026-03-12T19:23:34Z"
    mac: ENC[AES256_GCM,data:lDRv6kGSpcblw1ncA4cXZ5ffADnjHPat1bqTdZWdlU9MusRBPqIpVB2XH1B11EcJwqFmFJzu8pnAoqhnMm2jhNFAqht6HcBg+iSZjdhQr0YFjmxC1r9XOwddYSWJl1SuCmANP9GfM8niuJnHqOuNL9a1E9R3ZMPNmSbC4wbenRo=,iv:I9aDhW6Qe4v0rnQXpdmYoMVlAyrKWVWi5iKS9FGidpk=,tag:PsgUZhS7rhFEUhLbsE5/dw==,type:str]
    pgp:
        - created_at: "2026-03-12T19:23:34Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4Drti3Uh53xz4SAQdAFAhgi8isjiIfRZTvJT5qAmVyiEe/3rtKZ6NQ2SO4bF4w
            ofQqWU12BMOIsiOGkALYQ9bnSAzILoWu4kEJGF0ClFo9sup5Ft++7mmvSdue9g1S
            1GYBCQIQtsAkrIinwq23UTRZjeeNaDOLtBqr3hKZZDN8PHmdXCv9j2/8hrX04V8X
            60uDe+t/GMcbNQOUTFmjg+GqBsApVQrWNmGoJqz0d/k0UmfQ6+ccRvR/fA2AitOW
            SByENpnMgAY=
            =+uZ2
            -----END PGP MESSAGE-----
          fp: 8152E60988488774
    unencrypted_suffix: _unencrypted
    version: 3.12.1
