#ENC[AES256_GCM,data:zL3nzsBzeqMcbPGDxJ4Ljc7Z1Iybij2IsenEWF+S6Sxq46ZRyVWOxvfibeUXww75ptBFa2hnKU5NGYwDmoHaS2Q9IkirLyffazT8kBib/J347I9nfWzhYvbPG4+xrMLIWWWE48JrRb/dzQ5ultV3lIL6fTJtlSZU4kaowEA5adnCJofU7oZQjhvWRfWU8Q==,iv:UccZdGuRyq+Za8j6h7d4k+K0H5eqfUpQH0G7RgBpIdw=,tag:YJ6ShrhKUaDSjPtd10+paw==,type:comment]
auth:
    password: ENC[AES256_GCM,data:iuGjR9K5EXE=,iv:9VLwPUhaL7kkVIeubFTmO4z7xvD0bO+CdZr8EBIkEVM=,tag:x705oKwZnaPUcfukBeAEJA==,type:str]
sops:
    lastmodified: "2026-03-12T19:23:34Z"
    mac: ENC[AES256_GCM,data:XMxIE6MOPYpiSKvQudRcBWlFWMR4doSeNjS/IyBHbaX1E1dwTf5YilkJXBu9No/9/gsWlAOPpqd9PfMZvmwnQaMC5OWkqM0qEf6oEKYaiPG3NkOxdLLY7n+Sfl0XLD6uncUCUiiI+HjGXBuTGRS5xIDPhg9AOFrgmjEb1W/aJZE=,iv:yxOhDkkb0ING68ms2F/NhAs6bBGTK7pdlZzOrc97iR4=,tag:zcgq3AQQCS9tfO5tEfg/Pg==,type:str]
    pgp:
        - created_at: "2026-03-12T19:23:34Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4Drti3Uh53xz4SAQdABfvGWssjTWsYZ8wrxulqcErkDAnxxU4JJ8MC1+bxSCkw
            vFceNJ7aAw+vJgk5e/fayH1cIhj3600/6W7u77RxgeTaJaJslsU5GCVrc8VI+KOG
            1GYBCQIQzG2dYrPm8hndyUIbvPxNLJXd1DgaoSmaPAPkIzY06W4gISNNPMUtHLoZ
            t0bhr4luTW2wfQF1z0dANlU9hy893Jjx1B+GwvGvYAtyu/7UAGgcUFVnRpZBBFtj
            BU3aDjBlhF8=
            =XTsN
            -----END PGP MESSAGE-----
          fp: 8152E60988488774
    unencrypted_suffix: _unencrypted
    version: 3.12.1
