#ENC[AES256_GCM,data:TgXaWuc+G6XRgKOJXbZIaO05Ew==,iv:/aFHFiNUwdp8RJLRDlFQjDN2HgZg2cAxqzJiuGvqcTY=,tag:/5JH5aIWFNgCwWk1qzqygw==,type:comment]
sso:
    grafana:
        #ENC[AES256_GCM,data:p5rBhtkxCmzQVhznpuK2gZQ24ohfl5g75EdhGpAUl9nBoF5x7Dn/FCHtVj8ILPmbzzfi7HX46J6s5knQ7RSe/mklCms709k=,iv:/ibg+wSV2yrWHSpHl4YPxFaoM6Bx/lLejlVf7WU/CjI=,tag:ZfbeUUKbLMLN873l8LHhgw==,type:comment]
        client_id: ENC[AES256_GCM,data:toXw9z74OCUYD3WBabDL584uv2QQo5vX/FxmbL8pZ4U=,iv:CpygGOUJ9bO5pQ1UAamdQ5cjl40owK5eOYrjFtsncpU=,tag:2Q3tEbOctBeG6aSBRicwPQ==,type:str]
        #ENC[AES256_GCM,data:jn1ujgAUUMcd/xGxKIioVQGV9S5zk/Chf3ic8o6dUr/b5XrvzHq5Trna6SXpPyTmRnybag7BTl5ywwC7ceztbQ6g2fzoQHQEU4xY,iv:SuwY6U1v/LQHvWrINyIQazz1zRHnVjjv7Z5F/q+ZuvY=,tag:via29vQTPlU78JmpmSltgw==,type:comment]
        client_secret: ENC[AES256_GCM,data:afrenhXdvKtpLSmneT/QwGvQJNdagyJzLApcCsAwnKTSwhiU1nHcWkt+9C8tchpOWlmteWBZtsKrotNTaYt0RQ==,iv:L4VTeM9PQ1KwISdOE2A47fnSK9tzf7ovTHrW/X4iRz8=,tag:JV0Cu4a+YmZJ4qx5Q3hY5w==,type:str]
    admin:
        #ENC[AES256_GCM,data:WHA36Oil24VL01BPo5jyyXackLY=,iv:6mVJFh/Cd3rUxOftuViiskeO+yqJMO3MpD6uozRBBuk=,tag:853TsR5dodtdNjREcIfUgg==,type:comment]
        email: ENC[AES256_GCM,data:PNwfiq58UAeXPWRvBE3akjY=,iv:x4FyYNbo511f8mVAKM29CzwuzdN2RqwEOTX/88kRZHw=,tag:v8Vt0lGB0iooSEnek0zb/w==,type:str]
        #ENC[AES256_GCM,data:uHQnL/YsujmwNONrWmhB3dK595P+/No=,iv:1LMCycQeS1CkYIBjP92eJCyYIGfSzXkHD58WN8v2o1Q=,tag:DbiZbqYWH0x7zW1KoVoReA==,type:comment]
        password: ENC[AES256_GCM,data:pVX3jMcazCvfTAI=,iv:sJyjOBa5/0G6bPNCMKQuKJkR1SxMMQaFjekN+Tf+sBw=,tag:Jb1Ov0rhh0jtK2bqX/kZOA==,type:str]
    tekton:
        client_id: ENC[AES256_GCM,data:FmQkYy6bgf5Mnhr81rsboZ5SNvmGWVBezft5XJ4Kx7E=,iv:DGYHWXejFSsmhfI4RQ0gD2PNUQFm29uK85NTLpkCQXc=,tag:q/S8CJU+P+G6ipzTjaLMFA==,type:str]
        client_secret: ENC[AES256_GCM,data:3IPurOueNPx2/vw1YDZgDEt9+8AE+Wsmy93DOYL1IpWvcp267LWfqxyZChV5ga6uOYWBYqW9ua8SF6c2xTqSlw==,iv:z61s0qE054vmknQ5EiL4ssX2t9wzQEEFNkQUDK0oiRE=,tag:zirFQg9BNoSOf/gQntjDNA==,type:str]
        cookie_secret: ENC[AES256_GCM,data:YOVjO8ACkrDqu+2g1/+PgQfSUselYNUtO02vsmtCTIc=,iv:Vzza9ikbrCqfJU4ijgt7ZXOlmJdYc3IqKGau8gv96xg=,tag:CaZ90y1lqV7NP1CKHMs8lw==,type:str]
sops:
    lastmodified: "2026-06-26T05:01:08Z"
    mac: ENC[AES256_GCM,data:nXLVHVgxqRkYZsM6J+P3aHLiZxa2Mfn/CObJqhsHWMUfqU0Ia9+1l+gDb7smIqYYPNP6rJd00Ix358maqvQoZTDX3UsHfivFj5KIZ/ThB2/pi21Sm7/N9Fh2aijylDQd+tUI19/Gt8tXiOuOYf84o2FHiTgBgXAqLeLFHr5SDaI=,iv:nPX9kwWQ2yRjApV3QBVSmMeeVi2udZm+jTpJ8tH2q4g=,tag:7Fdg7zQA7NAFpPhYQMEnGg==,type:str]
    pgp:
        - created_at: "2026-06-07T05:50:51Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4Drti3Uh53xz4SAQdA08FJUU07i1el+ehQeHUx7tLHfvIdhnz6rYBUgffJpkQw
            HZd+oxIGPTXsw/3oYa/OX8sCQZYeVeNE35zRwWhqa/0y/de7ZJD4/grf1oYe5adS
            1GgBCQIQfAGKilxj7Y9aM/9Ow/Y5d+n5/O7w4njX8rX3zonDHb2PA31F7BmCAo7o
            CoWAcdhctQZfR0o5HsyYEOOkyxJ/KHol6e3qBWyNGuKz1hkgHkWZ5xuHQN/sYaek
            gyFxgWOBX8km0Q==
            =Iu5S
            -----END PGP MESSAGE-----
          fp: 8152E60988488774
    unencrypted_suffix: _unencrypted
    version: 3.12.1
