#ENC[AES256_GCM,data:u3ImtM8VaS7rdGoeG7cpwR8Nfw==,iv:lYzAo21vcM/HeQrcFmlmSNpMEV7RWj3aIXfbPy29pw0=,tag:rbUCxwANrTEWkhrfN28TtQ==,type:comment]
sso:
    grafana:
        #ENC[AES256_GCM,data:5M3Gtrnqfve2YbBs5+Wt5H3sw/TN7QjqrTfLm4D+xTBhDJHPZSEbbB1ybqrumnVF4pkcVBIJ0Mu8dH5nD6wt2L2Ls5H9u8k=,iv:MgDxm8R5/fUZjpQhdVndf/8E8/T0UzvdcJNdurXqOwg=,tag:UM73qTO1yP98bJL7x44K/A==,type:comment]
        client_id: ENC[AES256_GCM,data:cK6UfYZ6jsIPusI+5BVJTrv3+OX6oJZ4AsexZhk4ea8=,iv:Um9TepYDkLliNgu+CbuX3T30TW1umi6W+aRQhGc7GOk=,tag:azkw+8Klcy6jgJKPKJQmAw==,type:str]
        #ENC[AES256_GCM,data:q6g18YTQmo+UvCQLvQQgyTJVJRrQVSN8TOynYGZVWMdSindzBgGa0fWFXc2fCXj9Pc1+XjtUFkvkEgJ5hXJ921CeE4JlRttg0NR1,iv:QZmuS13SovAKOP17edprrla9x3nDWWKCf/AqErtptZA=,tag:QlpdNeqirT3n0Ljl2GXcKQ==,type:comment]
        client_secret: ENC[AES256_GCM,data:9VP/iuAp9GzVVVeEyXlsuST4VElfStHh8zoKlrn9ZYe0IRK/P/AY2fdOBoTgK0qiImIyiADLo5Euy+pjmjsLEA==,iv:Wzf945zOS5JBugbt4ef7gy+eOHNRK1xHuTMTsXWVFzk=,tag:3ylRtH8Fg5D6fNMndl2EIw==,type:str]
    admin:
        #ENC[AES256_GCM,data:plQbMGSTCjLSTbE8N3Y6LPkRxDo=,iv:xJUOQeUjC6KUB1p+9/JHdji3x1A8kQ9G1eI5Dq7JhI4=,tag:rQcnDIJEIvMf7wSFu7ggPQ==,type:comment]
        email: ENC[AES256_GCM,data:6cKeLpMQkiotPm/ONtffBQQ=,iv:om+/riAmNszJWip+5YhdgpQViSQZjWq4VyfzXRmaPsI=,tag:na8GYSdx5OvgH8Qwpgdr0Q==,type:str]
        #ENC[AES256_GCM,data:IRyajEgrlemsBpFhlE68haMsuWMVGhA=,iv:lLoTNSmg9jhSY46XyLdEJGF9moBY2oX3Q0EVD2kV+7E=,tag:SDDqel9wlZldLoDVvScPvw==,type:comment]
        password: ENC[AES256_GCM,data:KJpOZyyzZbH6tRo=,iv:oAXfVHKto3KBXW4bZYVztepn99eF7aw4RfCzOpgGa7E=,tag:msEtEo/yfAa0gBDsU0iRAg==,type:str]
sops:
    lastmodified: "2026-04-02T05:47:10Z"
    mac: ENC[AES256_GCM,data:tQCC2lfQXAxVWnPt0jS1ze4XZc3GXQzL8NaJ6iR/IwxBWgEdaaJkbEywZx9RmUQ0+whBtk7PJWR1X49LZrJc6aCHYXiaJPCtEVUdew+rxj530WV19TMALxzfjDM4cdjUWfC3Nxe6fQtV6B3iFZ8uzh0RNfh5EYih5EnreF0pBb4=,iv:KjR0H//j4Hgn0aQTq+zpGju4a39CxXzDtL5apISLag0=,tag:giEAQx8CgUovoPpxKR9kxw==,type:str]
    pgp:
        - created_at: "2026-04-02T05:47:10Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4Drti3Uh53xz4SAQdALyuDZGA57kKsSpvqAmaAJG5yeqXxrBwnHL/9ryPDJwww
            szz/CevyHAxqrCUkhijB1k0tqyEY6oOS/RSs7X8S1qFfsBo1w36uPp0pSrsisO9p
            1GgBCQIQf6ZLjb9RegRzv2pQ8g0teR8D6f+rP/cEw1/X0J4AcLlvI12zFTi/5use
            hsV6r/rb+O0uscHlmsxx2D7z5S1dgb7xG6Whs0jsfJHCRpYifJ6iXg/a5ORb3NR8
            QvCszE+WuMZxmQ==
            =yzgc
            -----END PGP MESSAGE-----
          fp: 8152E60988488774
    unencrypted_suffix: _unencrypted
    version: 3.12.1
