apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: hello-world
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/managed-by: helm
    app.kubernetes.io/part-of: argo-workflows-config
spec:
  serviceAccountName: {{ .Values.workflowServiceAccount }}
  entrypoint: main
  templates:
    - name: main
      container:
        image: {{ .Values.helloWorkflow.image | quote }}
        command: ["sh", "-c"]
        args: ["echo 'hello from argo workflows'"]
