#!/bin/bash
set -euo pipefail

source "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/../lib/colors.sh"

HELMFILE_DIR="$(cd "$(dirname "$0")/../.." && pwd)"
ENV="${1:-}"

if [[ -z "$ENV" ]]; then
    error "Usage: $0 <environment>"
    exit 1
fi

SECRETS_DIR="$HELMFILE_DIR/helmfile/environments/$ENV/secrets"
ENC_FILE="$SECRETS_DIR/velero.enc.yaml"

if [[ ! -d "$HELMFILE_DIR/helmfile/environments/$ENV" ]]; then
    error "Environment not found: $ENV"
    exit 1
fi

. "$(dirname "$0")/../lib/terraform-env.sh"

# --- Extract Terraform outputs ---

header "Extracting Terraform outputs — $ENV"
echo ""

terraform -chdir="$HELMFILE_DIR/terraform" workspace select "$ENV"

BUCKET=$(terraform -chdir="$HELMFILE_DIR/terraform" output -raw velero_bucket_name)
ENDPOINT=$(terraform -chdir="$HELMFILE_DIR/terraform" output -raw velero_s3_endpoint)

success "velero_bucket_name: $BUCKET"
success "velero_s3_endpoint: $ENDPOINT"
echo ""

# --- Write and encrypt ---

mkdir -p "$SECRETS_DIR"
SECRETS_FILE=$(mktemp --suffix=.yaml)

PREFIX=$(yq '.velero.prefix' "$HELMFILE_DIR/helmfile/environments/$ENV/config.yaml")

cat > "$SECRETS_FILE" <<EOF
# Generated by velero-secrets.sh — values in Helm chart format so they are
# applied directly by helmfile without going through gotmpl .Values rendering.
configuration:
  backupStorageLocation:
    - name: default
      provider: aws
      bucket: "$BUCKET"
      prefix: "$PREFIX"
      credential:
        name: velero
        key: cloud
      config:
        region: auto
        s3ForcePathStyle: "true"
        s3Url: "$ENDPOINT"

credentials:
  secretContents:
    cloud: |
      [default]
      aws_access_key_id=$CLOUDFLARE_R2_ACCESS_KEY_ID
      aws_secret_access_key=$CLOUDFLARE_R2_SECRET_ACCESS_KEY
EOF

# Idempotency: sops --encrypt always produces a fresh IV/MAC, so re-encrypting
# unchanged content rewrites velero.enc.yaml on every install (noisy git diffs).
# Skip the write when the decrypted current secret already matches the new one
# (compared semantically, ignoring comments/formatting).
if [[ -f "$ENC_FILE" ]] && \
   diff -q <(sops --decrypt "$ENC_FILE" 2>/dev/null | yq -P '... comments=""') \
           <(yq -P '... comments=""' "$SECRETS_FILE") >/dev/null 2>&1; then
    rm -f "$SECRETS_FILE"
    echo ""
    success "velero secret unchanged — kept $ENC_FILE"
    exit 0
fi

sops --encrypt "$SECRETS_FILE" > "$ENC_FILE"
rm "$SECRETS_FILE"

echo ""
success "Updated $ENC_FILE"
